.gitignore, ZcashLightClientKit.podspec, ZcashLightClientKit/zcashlc/zcashlc.h
This fixes an error upon `pod trunk push` where the zcashlc.h file was nowhere to be found.
We will improve the build system to be autogenerating this h file properly soon.
=> Header fix

README.md
This current URL will redirect proper, but the lightwalletd repo is now in zcash org
=> Update lightwalletd url

ZcashLightClientKit/Block/Processor/CompactBlockDownloadOperation.swift, ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift, ZcashLightClientKit/Block/Processor/CompactBlockValidationInformation.swift, ZcashLightClientKit/Block/Processor/ZcashOperation.swift, ZcashLightClientKitTests/CompactBlockReorgTests.swift
Reorg could fail without an error message because of the operation that presented the error could be deallocated and nil'd before the error could be captured.
Fix: implement block operations adapters, that serve as safe walls between operations and enforce dependencies.
=> FIX: race condition on reorgs

Cargo.lock, Cargo.toml, Example/ZcashLightClientSample/Podfile.lock
=> Update LibRustZcash revision to support canopy on TESTNET

ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift, ZcashLightClientKit/Block/Processor/ZcashOperation.swift, ZcashLightClientKit/UIKit/Synchronizer/SDKSynchronizer.swift, ZcashLightClientKitTests/TestCoordinator.swift
closes #176 
closes https://github.com/zcash/zcash-ios-wallet/issues/137
closes https://github.com/zcash/zcash-ios-wallet/issues/123
Reported by: Unstoppable Wallet
> When the app goes to background, it calls synchronizer.stop, invalidates timer and sets state to stopped. But ZCashOperation class calls start() and it is trying to download more data with new state 'validating'. After canceling tasks, kit does not set 'stopped' state again. So, when we come back from background, state has not setted to 'stopped'. Is it right behavior?
````
18:23:20.046 💚 DEBUG  ZcashOperation  start()  42 : <ZcashLightClientKit.CompactBlockDownloadOperation: 0x135ec0de0>{name = 'Download Operation: 1038100...1038199'} started
(CBProcessor) set state: downloading
==> call synchronizer.stop
=====> …
```
=> Synchronizer Enhancements: Operations cancelled when going to background

Cargo.lock, Cargo.toml, ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift, ZcashLightClientKit/Entity/TransactionEntity.swift, ZcashLightClientKit/Synchronizer.swift, ZcashLightClientKit/UIKit/Synchronizer/SDKSynchronizer.swift, ZcashLightClientKitTests/RewindRescanTests.swift
=> Allow Wallet developers to rewind synchronizer and (eventually) rescan

Cargo.lock, Cargo.toml, rust/src/lib.rs
@nuttycom these are the fixes I managed to create to compensate those derivation functions no longer present on librustzcash
these should go soon when we do library support for NU5
=> Fix derive_transparent_address_from... compile errors

Package.resolved, Package.swift, ZcashLightClientKit.podspec, changelog.md
Closes #389 
This solves a problem where an NU5 aware wallet would receive a
v5 transaction with sapling funds and wouldn’t be able to
enhance it by decrypting the full transaction.
This works in conjunction with lightwalletd version v0.4.11 and .12
see https://github.com/zcash/lightwalletd/releases/tag/v0.4.12
and https://github.com/zcash/lightwalletd/releases/tag/v0.4.11
for details on how to upgrade your light client infrastructure.
=> [#388] Integrate libzcashlc 0.0.3 to support v5 transaction parsing

Sources/ZcashLightClientKit/Block/DatabaseStorage/CompactBlockStorage.swift, Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/DAO/PagedTransactionDao.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift, Tests/TestUtils/FakeService.swift
Closes #435 (partially)
This commit is mostly motivated from Thread sanitizer warnings from ECC Wallet.
There is yet one outstanding warning caused by Swift-GRPC which needs that the stack is initialized on a second thread with .default QoS. 
Wallets using Combine need to gather information from several notification when in fact that information originates at the same time. We gathered all that info and created a SynchronizerState struct that condenses wallet balance, scanned height, etc. this allows these wallets not to poll the synchronizer for info unnecessarily.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth …
=> 435 thread sanitizer issue

Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift, Tests/TestUtils/Tests+Utils.swift
Closes #541 
MultiThreadedEventLoopGroup has been replaced with NIOTSEventLoopGroup. It's recommended by authors of grpc-swift especially for iOS platform and it allows us to set the priority because NIOTSEventLoopGroup is GCD based while MultiThreadedEventLoopGroup is pthread based.
From the authors
```
/// In general, when building applications whose primary purpose is to be deployed on Darwin
/// platforms, the `NIOTSEventLoopGroup` should be preferred over the
/// `MultiThreadedEventLoopGroup`. In particular, on iOS, the `NIOTSEventLoopGroup` is the
/// preferred networking backend.
```
DarkSideTests
Kudos to @Chlup for co-working on this one.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all …
=> [#541] Initialise gRPC on a separate thread

Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift, Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanning.swift, Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift, Sources/ZcashLightClientKit/Constants/ZcashSDK.swift, Tests/NetworkTests/BlockScanTests.swift, Tests/NetworkTests/BlockStreamingTest.swift, Tests/NetworkTests/CompactBlockProcessorTests.swift, Tests/NetworkTests/CompactBlockReorgTests.swift
- It makes sense to have only one downloading stream for blocks even when processing blocks in parallel. Especially on mobile devices we can expect that internet connection won't be super fast.
- And it makes sense to not rely on some magic inside gRPC library and be sure that there always be only one download stream no matter what.
- Disadvantage of this approach is that there is no real parallelisation until we can scan in parallel. With this one stream approach we have multiple tasks but only one runs at the time.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please …
=> Use only one stream when processing blocks in parallel

CHANGELOG.md, Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
- When rewind is called during sync then exception is thrown.
=> [#651] Fix rewind when it's called during sync

CHANGELOG.md, Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
This is just hotfix that disables removing of cache DB.
=> [#660] Fix the situation when any rewind causes full rescan

Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift, Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift, Package.resolved, Package.swift, Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift, Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanning.swift, Sources/ZcashLightClientKit/Block/Processor/CompactBlockValidationInformation.swift, Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift, Sources/ZcashLightClientKit/Constants/ZcashSDK.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Tests/DarksideTests/ShieldFundsTests.swift, Tests/DarksideTests/TransactionEnhancementTests.swift, Tests/NetworkTests/BlockScanTests.swift, Tests/NetworkTests/BlockStreamingTest.swift, Tests/NetworkTests/CompactBlockProcessorTests.swift, Tests/NetworkTests/CompactBlockReorgTests.swift, Tests/OfflineTests/BlockBatchValidationTests.swift, Tests/OfflineTests/CompactBlockProcessorOfflineTests.swift, Tests/OfflineTests/InternalSyncProgressTests.swift, Tests/TestUtils/FakeStorage.swift
Closes #657
- Now SDK downloads N downloads and scan those. And repeat until sync is done. This safes lot of space of disk used to store downloaded blocks.
- Most changes are done in `CompactBlockProcessor.processNewBlocks`.
- `SyncRanges` structure is changed a bit.
- `SyncStatus` is changed. SDK now report that it's syncing with progress. It doesn't report each phase of the sync process separately. Also appropriate notifications were updated.
=> [#657] Change how blocks are downloaded and processed

Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Previously `SDKSynchronizer` simply refused to start while the sync process was in progress. That could lead to some troubles. `CompactBlockProcessor` has already mechanism which can handle this exact situation. So now `SDKSynchronizer` starts `CompactBlockProcessor` even when there is sync in progress.
=> [#657] Fix start of SDKSynchronizer when sync is already in process

.swiftlint.yml, CHANGELOG.md, Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Block/FetchUnspentTxOutputs/UTXOFetcher.swift, Sources/ZcashLightClientKit/Block/FilesystemStorage/FSCompactBlockRepository.swift, Sources/ZcashLightClientKit/DAO/NotesDao.swift, Sources/ZcashLightClientKit/Initializer.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Tests/DarksideTests/AdvancedReOrgTests.swift, Tests/DarksideTests/InternalStateConsistencyTests.swift, Tests/DarksideTests/PendingTransactionUpdatesTest.swift, Tests/DarksideTests/ReOrgTests.swift, Tests/DarksideTests/SynchronizerTests.swift, Tests/DarksideTests/TransactionEnhancementTests.swift, Tests/NetworkTests/BlockScanTests.swift, Tests/NetworkTests/CompactBlockProcessorTests.swift, Tests/NetworkTests/CompactBlockReorgTests.swift, Tests/TestUtils/CompactBlockProcessorEventHandler.swift
Closes #764
- All notification that were previously sent from CompactBlockProcessor are now gone.
- `CompactBlockProcessor` now provides `eventStream` to communicate with `SDKSynchronizer`.
- Added `synchronizerStoredUTXOs` notification.
- Tests are updated to not use notifications anymore. Some tests there weren't working before are now fixed.
- Added `CompactBlockProcessorEventHandler` utility class. Previously expectations were subscribing to notifications. This class replaces this functionality. It subscribes to events from `CompactBlockProcessor` and fullfill expectations.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more …
=> [#764] Stop using Notifications inside the SDK

.swiftlint.yml, .swiftlint_tests.yml, CHANGELOG.md, Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift, Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift, Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift, Example/ZcashLightClientSample/ZcashLightClientSample/ViewController.swift, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Block/Utils/AfterSyncHooksManager.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Tests/DarksideTests/SychronizerDarksideTests.swift, Tests/DarksideTests/SynchronizerTests.swift
Closes #801
- `SDKSynchronizer.wipe()` can be now called anytime.
- If the sync is in progress then the sync is first stopped and then wipe is executed.
- Wipe now returns AnyPublisher which completes or fails when wipe is done.
- Majority of wipe's work is to delete files. That is only operation
that can throw error during wipe. This operation should succeed every
time. If it fails that something is seriously wrong. When this happens
the SDK can happen in inconsistent state. There is no recovery for
now. Only way how to fix this is to reinstall the app in the device.
- Added hooks mechanism. This is implemented in `AfterSyncHooksManager`
and it is used by `CompactBlockProcessor`. It's just more organized
way how to track what should happen when the sync process is canceled.
This code …
=> [#801] Improve wipe implementation

CHANGELOG.md, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Block/Utils/AfterSyncHooksManager.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Tests/DarksideTests/RewindRescanTests.swift, Tests/DarksideTests/SynchronizerTests.swift
Closes #816
- `SDKSynchronizer.rewind(policy:)` can be now called anytime.
- If the sync is in progress then the sync is first stopped and then rewind is executed.
- Rewind now returns AnyPublisher which completes or fails when wipe is done.
- `AgterSyncHooksManager` is used to execute rewind after sync process is stopped.
=> [#816] Improve how rewind(policy:) call can be used

CHANGELOG.md, Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift, Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift, Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift, MIGRATING.md, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Block/Enhance/BlockEnhancer.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Tests/DarksideTests/BalanceTests.swift, Tests/DarksideTests/InternalStateConsistencyTests.swift, Tests/DarksideTests/SychronizerDarksideTests.swift, Tests/DarksideTests/SynchronizerTests.swift, Tests/DarksideTests/Z2TReceiveTests.swift, Tests/PerformanceTests/SynchronizerTests.swift, Tests/TestUtils/SDKSynchronizerSyncStatusHandler.swift, Tests/TestUtils/TestCoordinator.swift, Tests/TestUtils/Tests+Utils.swift
Closes #724
- All the notifications are gone. Only
`synchronizerConnectionStateChanged` stayed because it's used
internally. Let's deal with this one in another task.
- Synchronizer has now two new publishers (`stateStream` and
(`eventStream`) which are used to notify the client app about
what is going on. These publishers replace notifications.
- There is also new property `latestState` which can be used to get the
SDK state in synchronous manner.
- `SDKSynchronizer.status` is no longer public. It is used internally to
refresh `latestState` and emit new values from `stateStream`.
- When `SDKSynchronizer.status` is update `notify()` function is
triggered. And this function is now responsible for generating new
snapshot of `SynchronizerState` and updating `latestState` and
`stateStream`. …
=> [#724] Switch from NotificationCenter to Combine

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Block/Utils/AfterSyncHooksManager.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Sources/ZcashLightClientKit/Utils/GenericActor.swift, Tests/DarksideTests/AdvancedReOrgTests.swift, Tests/DarksideTests/InternalStateConsistencyTests.swift, Tests/DarksideTests/ReOrgTests.swift, Tests/DarksideTests/SynchronizerTests.swift, Tests/DarksideTests/TransactionEnhancementTests.swift, Tests/NetworkTests/BlockScanTests.swift, Tests/NetworkTests/CompactBlockProcessorTests.swift, Tests/NetworkTests/CompactBlockReorgTests.swift, Tests/TestUtils/CompactBlockProcessorEventHandler.swift
- In general lot of methods inside the `SDKSynchronizer` and `CompactBlockProcessoer` which weren't async are now async. And other changes are made because of this change.
- `CompactBlockProcessor` no longer uses Combine to communicate with `SDKSynchronizer`. Reason for this is that Combine doesn't play great with async. Closure passed to `sink` isn't async.
- Because of this and because of how our tests work (receiving signals from CBP directly) `CompactBlockProcessor` must be able to handle more event closures. Not just one. So it now has `eventClosures` dictionary. It's little bit strange but it works fine.
- `SyncStatus` inside the `SDKSynchronizer` was previously protected by lock. Now it's protected by simple actor wrapper.
- Changes in tests are minimal. Changes were mady only …
=> [#831] Use async inside of the SDKSynchronizer

Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift, Sources/ZcashLightClientKit/Extensions/URL+UpdateWithAlias.swift, Sources/ZcashLightClientKit/Initializer.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Tests/OfflineTests/InitializerOfflineTests.swift, Tests/OfflineTests/SynchronizerOfflineTests.swift, Tests/OfflineTests/WalletTests.swift, Tests/PerformanceTests/SynchronizerTests.swift, Tests/TestUtils/TestCoordinator.swift
Closes #851.
- `Initializer` now updates paths according to alias before paths are used anywhere in the SDK.
- Paths update can fail. It would be incovenient for the client apps to handle errors thrown from `Initiliazer` constructor. So the error is then handled in `SDKSynchronizer.prepare()` or `SDKSynchronizer.wipe()`.
=> [#851] Apply the Alias to the URLs

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/xcshareddata/xcschemes/All.xcscheme, Package.swift, Sources/ZcashLightClientKit/Initializer.swift, Tests/AliasDarksideTests/SDKSynchronizerAliasDarksideTests.swift, Tests/AliasDarksideTests/scripts/kill_and_clean_servers.zsh, Tests/AliasDarksideTests/scripts/run_darkside_servers.zsh, Tests/AliasDarksideTests/scripts/servers_config.zsh, Tests/DarksideTests/BlockDownloaderTests.swift, Tests/TestUtils/DarkSideWalletService.swift, Tests/TestUtils/TestCoordinator.swift, Tests/TestUtils/Tests+Utils.swift
Closes #876.
- Add `testMultipleSynchronizersCanRunAtOnce()` test which creates multiple instances of the `SDKSynchronizer` and then executes sync in paralell.
- To achieve this it's required to have multiple instances of the lightwalletd in the darkside mode. Because of this new test is in the new target `AliasDarksideTests`. It's little bit harder to run this test than to run regular darkside tests. So it has it's own target.
- Fix bug when all the instances of the `SDKSynchronizer` used same data DB even with different aliases.
- Add script to run multiple instances of the lightwalletd in darkside mode. And add script to stop these instances and clean after those.
- Update `DarksideWalletService` a little so the endpoint can be passed to it. Without this it would always use default …
=> [#876] Add tests which runs multiple instances of the SDKSynchronizer

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Sources/ZcashLightClientKit/Utils/SyncSessionIDGenerator.swift, Tests/DarksideTests/SynchronizerDarksideTests.swift, Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift, Tests/OfflineTests/CombineSynchronizerOfflineTests.swift, Tests/OfflineTests/SynchronizerOfflineTests.swift, Tests/TestUtils/MockSessionIDGenerator.swift, Tests/TestUtils/SDKSynchronizer+Utils.swift, Tests/TestUtils/TestCoordinator.swift
Closes #895 
Add Sync Session ID to `SynchronizerState`.
A SyncSession is an attempt to sync the blockchain within the lifetime of a Synchronizer.
A Synchronizer can sync many times, when synced it will refresh every ~20 seconds +- random padding.
each sync attempt will have a different UUID even if it's from the same instance of SDKSynchronizer.
**How are SyncSessions are delimited? With `SyncStatus` changes.** 
changes from [`.unprepared`|`.error`|`.disconnected`|`.stopped`] to `.syncing` assign a new sessionID to the synchronizer.
Any other transitions won't. 
`areTwoStatusesDifferent ` was refactored to a helper function of `SyncStatus`
**How are IDs generated?**
ID generation is not mandated but delegated to a protocol `SyncSessionIDGenerator`.
Tests inject their own deterministic …
=> Add Sync Session ID Synchronizer State

.swiftlint.yml, Package.swift, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Error/Sourcery/ZcashError.stencil, Sources/ZcashLightClientKit/Error/Sourcery/ZcashErrorCode.stencil, Sources/ZcashLightClientKit/Error/Sourcery/generateErrorCode.sh, Sources/ZcashLightClientKit/Error/ZcashError.swift, Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift, Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift, Sources/ZcashLightClientKit/Modules/Service/GRPC/LightWalletGRPCService.swift, Sources/ZcashLightClientKit/Modules/Service/LightWalletService.swift, Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift, Tests/TestUtils/DarkSideWalletService.swift, Tests/TestUtils/FakeService.swift, Tests/TestUtils/Stubs.swift
This PR introduces `ZcashError` enum. This enum represents any error that can be thrown inside of the SDK and outside of the SDK. Also `ZcashError` is used in `LightWalletGRPCService` and handled in `CompactBlockProcessor` as example.
Why enum? First I tried this with some structure which contained code, message and underlyingError. Problem was when some specific place in the SDK would like to attach some additional data to error. I didn't want to add some generic dictionary to store anything with the error.
So I used enum to identify error. Each member can have specified amount of associated values. So specific error can bring some context data. And it's type safe.
Each error has also a code. Relationship between errors and codes is 1:1. It may looks bit redundant but it's important. The …
=> [#361] Introduce ZcashError

.github/workflows/swift.yml, Tests/AliasDarksideTests/SDKSynchronizerAliasDarksideTests.swift, Tests/DarksideTests/AdvancedReOrgTests.swift, Tests/DarksideTests/BalanceTests.swift, Tests/DarksideTests/DarksideSanityCheckTests.swift, Tests/DarksideTests/InternalStateConsistencyTests.swift, Tests/DarksideTests/PendingTransactionUpdatesTest.swift, Tests/DarksideTests/ReOrgTests.swift, Tests/DarksideTests/RewindRescanTests.swift, Tests/DarksideTests/ShieldFundsTests.swift, Tests/DarksideTests/SynchronizerDarksideTests.swift, Tests/DarksideTests/SynchronizerTests.swift, Tests/DarksideTests/TransactionEnhancementTests.swift, Tests/DarksideTests/Z2TReceiveTests.swift, Tests/NetworkTests/CompactBlockProcessorTests.swift, Tests/NetworkTests/CompactBlockReorgTests.swift, Tests/NetworkTests/LightWalletServiceTests.swift, Tests/OfflineTests/SynchronizerOfflineTests.swift, Tests/PerformanceTests/SynchronizerTests.swift
Closes #901
- Swift 5.8 throws warning when `wait` is used in async context. And it suggests to use `fulfillment`. It works fine. And `fulfillment` is available from Xcode 11. So there is not problem with backwards compatibility.
=> [#901] Use fulfillment instead of wait in async context in tests

CHANGELOG.md, Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksListViewController.swift, README.md, Sources/ZcashLightClientKit/Initializer.swift, Sources/ZcashLightClientKit/Utils/LoggingProxy.swift, Tests/OfflineTests/InitializerOfflineTests.swift, Tests/OfflineTests/SynchronizerOfflineTests.swift, Tests/PerformanceTests/SynchronizerTests.swift, Tests/TestUtils/TestCoordinator.swift
The `Initializer` struct now takes a `LoggingPolicy` parameter, which enables the following options when initializing the SDK:
- `default` - the SDK will default to using its own internal implementation of the `Logger` protocol at the `debug` log level. You can also override the log level by passing your preferred log level in to the enum case.
- `custom` - the user provides an object conforming to the `Logger` protocol, allowing for complete customizability of the logging.
- `noLogging` - the SDK will not log anything
Closes #1013 
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about …
=> [#1013] - Enable more granular control over logging behavior

Sources/ZcashLightClientKit/Block/Actions/ComputeSyncRangesAction.swift, Sources/ZcashLightClientKit/Block/Actions/DownloadAction.swift, Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift, Sources/ZcashLightClientKit/Block/Actions/MigrateLegacyCacheDBAction.swift, Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift, Sources/ZcashLightClientKit/Block/Actions/ValidateServerAction.swift, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Tests/AliasDarksideTests/SDKSynchronizerAliasDarksideTests.swift, Tests/DarksideTests/AdvancedReOrgTests.swift, Tests/DarksideTests/BalanceTests.swift, Tests/DarksideTests/DarksideSanityCheckTests.swift, Tests/DarksideTests/InternalStateConsistencyTests.swift, Tests/DarksideTests/PendingTransactionUpdatesTest.swift, Tests/DarksideTests/ReOrgTests.swift, Tests/DarksideTests/RewindRescanTests.swift, Tests/DarksideTests/ShieldFundsTests.swift, Tests/DarksideTests/SynchronizerDarksideTests.swift, Tests/DarksideTests/SynchronizerTests.swift, Tests/DarksideTests/Z2TReceiveTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ComputeSyncRangesActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/DownloadActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/EnhanceActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ScanActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ValidateServerActionTests.swift, Tests/TestUtils/TestCoordinator.swift
Closes #1102
Some tests that can't be compiled are disabled for now. List is in #1126.
This PR contains multiple fixes. Most of the fixes is done in the code. Not in the tests. That is good news.
Fixes:
- `config` inside `CompactBlockProcessor` can be updated during the tests. And it must be also updated inside the actions. So `ConfigProvider` is added and it is wrapper for config that is passed to any instance of `Action` and provides updated config.
- Fixed `EnhanceAction`. Now it should update all the blocks in the enhance range even when the remaining count of blocks is lower than 1000.
- Fixed `fail()` and `validationFailed()`. These two were canceling `syncTask`. But that stopped run loop in a bad way.
This code review checklist is intended to serve as a starting point for the …
=> [#700] Fix DarksideTests

CHANGELOG.md, Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift, Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksListViewController.swift, Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift, Sources/ZcashLightClientKit/Block/Actions/Action.swift, Sources/ZcashLightClientKit/Block/Actions/ProcessSuggestedScanRangesAction.swift, Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Block/Scan/BlockScanner.swift, Sources/ZcashLightClientKit/Block/Utils/CompactBlockProgress.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Closes #1181 
- the computation of progress changed, the total range is computed, that way it works for any kind of sync algorithm
- the progress depends on finished scan action, whenever it processes some blocks, it's counted up
- the final progress is a ratio between these new values
=> [#1181] Correct computation of progress for Spend before Sync

Tests/AliasDarksideTests/SDKSynchronizerAliasDarksideTests.swift, Tests/DarksideTests/AdvancedReOrgTests.swift, Tests/DarksideTests/BalanceTests.swift, Tests/DarksideTests/DarksideSanityCheckTests.swift, Tests/DarksideTests/PendingTransactionUpdatesTest.swift, Tests/DarksideTests/ReOrgTests.swift, Tests/DarksideTests/RewindRescanTests.swift, Tests/DarksideTests/ShieldFundsTests.swift, Tests/DarksideTests/SynchronizerDarksideTests.swift, Tests/DarksideTests/SynchronizerTests.swift, Tests/DarksideTests/Z2TReceiveTests.swift, Tests/TestUtils/DarkSideWalletService.swift, Tests/TestUtils/FakeChainBuilder.swift, Tests/TestUtils/TestCoordinator.swift, Tests/TestUtils/proto/darkside.grpc.swift, Tests/TestUtils/proto/darkside.pb.swift, Tests/TestUtils/proto/darkside.proto
Depends on https://github.com/zcash/lightwalletd/pull/448.
=> Migrate to latest `darkside.proto` to help fix Darkside tests

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift, Package.resolved, Package.swift, Sources/ZcashLightClientKit/Block/Actions/Action.swift, Sources/ZcashLightClientKit/Block/Actions/ClearCacheAction.swift, Sources/ZcashLightClientKit/Block/Actions/DownloadAction.swift, Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift, Sources/ZcashLightClientKit/Block/Actions/ProcessSuggestedScanRangesAction.swift, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Tests/NetworkTests/BlockStreamingTest.swift, Tests/OfflineTests/CompactBlockProcessorActions/ActionContextStateTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ClearAlreadyScannedBlocksActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ClearCacheActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ComputeSyncControlDataActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/DownloadActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/EnhanceActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/FetchUTXOsActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/MigrateLegacyCacheDBActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ProcessSuggestedScanRangesActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/RewindActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/SaplingParamsActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ScanActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/UpdateChainTipActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/UpdateSubtreeRootsActionTests.swift, Tests/OfflineTests/CompactBlockProcessorActions/ValidateServerActionTests.swift, Tests/OfflineTests/SynchronizerOfflineTests.swift, Tests/TestUtils/ActionContext+tests.swift, Tests/TestUtils/Sourcery/AutoMockable.swift, Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Closes #1176 
- all tests updated to handle both .linear and .spendBeforeSync algorithms
- package.resolved updated
- added tests for brand new actions related Spend before Sync:
- RewindActionTests
- UpdateChainTipActionTests
- UpdateSubtreeRootsActionTests
- ProcessSuggestedScanRangesActionTests
=> [#1176] Cover Spend before Sync with tests

Sources/ZcashLightClientKit/Block/Actions/UpdateSubtreeRootsAction.swift, Tests/OfflineTests/CompactBlockProcessorActions/UpdateSubtreeRootsActionTests.swift
Closes #1179 
- when getSubtreeRoots call fails on timeout, the connectivity is not present and the action must be terminated (throw) an error, this way when the connectivity is back, the State Machine starts over and getSubtreeRoots get a chance to properly decide if SBS is supported
- unit test for the timeout getSubtreeRoot added
=> [#1179] Handle false positive getSubtreeRoots when connectivity is down

Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift, Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift, Sources/ZcashLightClientKit/Initializer.swift, Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Closes #1232 
- createAccount when there are none is called
- sample app send screen improvements (balance automatically refreshes)
- TODO for the recoverUntil parameter
=> [#1232] Implement createAccount

Tests/DarksideTests/AdvancedReOrgTests.swift, Tests/DarksideTests/BalanceTests.swift, Tests/DarksideTests/DarksideSanityCheckTests.swift, Tests/DarksideTests/PendingTransactionUpdatesTest.swift, Tests/DarksideTests/RewindRescanTests.swift, Tests/DarksideTests/SynchronizerDarksideTests.swift, Tests/DarksideTests/SynchronizerTests.swift, Tests/DarksideTests/TransactionEnhancementTests.swift, Tests/DarksideTests/Z2TReceiveTests.swift, Tests/NetworkTests/BlockStreamingTest.swift, Tests/NetworkTests/CompactBlockProcessorTests.swift, Tests/NetworkTests/CompactBlockReorgTests.swift, Tests/PerformanceTests/SDKMetricsTests.swift, Tests/PerformanceTests/SynchronizerTests.swift
Closes #1242 
- DarkSide, Network and Performance tests were modified to be buildable again
=> [#1242] Fix unit tests after SBS changes

.github/workflows/swiftlint.yml, Sources/ZcashLightClientKit/Checkpoint/BundleCheckpointSource.swift, Sources/ZcashLightClientKit/Modules/Service/LightWalletService.swift, Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
Closes #1332.
This runs an ubuntu box with a swiftlint process and nothing else.
During implementing this same thing in the ZIP-321 library I found that the Swift Package Plugin for Swiftlint did work after some juggling, but it added a lot of build time to the main build job so it delayed the CI for several minutes while a separate machine would to the same chore more effectively and also in an isolated way without mixing lint and build failures
=> [#1332] Enable Swiftlint workflow

Sources/ZcashLightClientKit/Error/ZcashError.swift, Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Closes #1374 
- ZcashError generated code updated
=> [#1374] ZashiError generated code update is missing

CHANGELOG.md, Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift, Sources/ZcashLightClientKit/ClosureSynchronizer.swift, Sources/ZcashLightClientKit/CombineSynchronizer.swift, Sources/ZcashLightClientKit/Model/Proposal.swift, Sources/ZcashLightClientKit/Modules/Service/GRPC/ProtoBuf/proposal.pb.swift, Sources/ZcashLightClientKit/Modules/Service/GRPC/ProtoBuf/proto/proposal.proto, Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift, Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/ClosureSDKSynchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/CombineSDKSynchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift, Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift, Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift, Tests/TestUtils/Stubs.swift
Closes Electric-Coin-Company/zcash-swift-wallet-sdk#1343.
=> Expose APIs for working with transaction proposals

Sources/ZcashLightClientKit/Block/Scan/BlockScanner.swift, Sources/ZcashLightClientKit/Modules/Service/GRPC/LightWalletGRPCService.swift, Sources/ZcashLightClientKit/Modules/Service/LightWalletService.swift, Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift, Sources/ZcashLightClientKit/Synchronizer/Dependencies.swift, Tests/TestUtils/DarkSideWalletService.swift, Tests/TestUtils/FakeService.swift, Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift, Tests/TestUtils/Stubs.swift
- @str4d please check this implementation, I believe it's what you were looking for.
- the new service's method getTreeState needs some documentation though
=> TreeState support

CHANGELOG.md, Example/ZcashLightClientSample/ZcashLightClientSample/Get Balance/GetBalanceViewController.swift, Sources/ZcashLightClientKit/ClosureSynchronizer.swift, Sources/ZcashLightClientKit/CombineSynchronizer.swift, Sources/ZcashLightClientKit/Model/FiatCurrencyResult.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/ClosureSDKSynchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/CombineSDKSynchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Sources/ZcashLightClientKit/Tor/TorClient.swift, Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
- API refactored to Combine's CurrentValueSubject
=> refresh-rates

CHANGELOG.md, Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.pbxproj, Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Example/ZcashLightClientSample/ZcashLightClientSample/Base.lproj/Main.storyboard, Example/ZcashLightClientSample/ZcashLightClientSample/Test Servers/TestServersViewController.swift, Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift, Sources/ZcashLightClientKit/Constants/ZcashSDK.swift, Sources/ZcashLightClientKit/Synchronizer.swift, Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift, Tests/TestUtils/FakeChainBuilder.swift
Close #1466 
- `evaluateBestOf(endpoints)` async method implemented. It takes a list of endpoints and evaluates the performance of each, rule out some during the process and returns top `k` best servers.
=> [#1466] Choose the best server by testing responses from multiple hosts
