ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
ZcashLightClientKit/Stencil/ZcashSDK.stencil

Addresses #71 
There are better approaches at the expense of more research time.

Randomize POLL_INTERVAL

---

ZcashLightClientKit.podspec

Contains fixes for issues:
#71

Release 0.1.1

---

ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
ZcashLightClientKitTests/CompactBlockProcessorTests.swift

Fix - CompactBlock Processsor loops indefinitely on reorg

---

ZcashLightClientKit/Rust/ZcashRustBackend.swift
ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
ZcashLightClientKit/UIKit/Synchronizer/SDKSynchronizer.swift

Changes to createToAddress function to fix issues with paths that have spaces
Synchronizer:
change from computed variables to functions to allow throwing errors to clients

Synchronizer enhancements

---

Cargo.lock
Cargo.toml
ZcashLightClientKit/Rust/ZcashRustBackend.swift
ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
ZcashLightClientKit/zcashlc/zcashlc.h
rust/src/lib.rs

Also updates the Rust dependencies.

ZcashRustBackend.decryptAndStoreTransaction()

---

ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
ZcashLightClientKit/Transaction/TransactionEncoder.swift
ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
ZcashLightClientKitTests/BalanceTests.swift

Fixes isu 136 - expiry height -1 on pending transactions

---

.travis.yml
Example/ZcashLightClientSample/Podfile
Scripts/travis/ZcashLightClientSample_setup.sh
Scripts/travis/rust_setup.sh

Builds using travis' xcode11.5 image

Add a .travis.yml file

---

ZcashLightClientKit/Entity/PendingTransactionEntity.swift

bugs on pending transactions convenient methods for wallets

enhance pending transaction handling

---

ZcashLightClientKit/DAO/PendingTransactionDao.swift
ZcashLightClientKit/Repository/PendingTransactionRepository.swift
ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
ZcashLightClientKit/UIKit/Synchronizer/SDKSynchronizer.swift
ZcashLightClientKitTests/AdvancedReOrgTests.swift
ZcashLightClientKitTests/PendingTransactionUpdatesTest.swift

Fixes #158 #132 #134 #135 #133

Pending tx wont clear

---

README.md

#177 workaround until better solution is  implemented

add workaround to fix rustc problem on init accounts

---

ZcashLightClientKit/DAO/TransactionDao.swift

fixes https://github.com/zcash/zcash-ios-wallet/issues/183

Fix findAll transactions query

---

Example/ZcashLightClientSample/Podfile
Example/ZcashLightClientSample/Podfile.lock
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.pbxproj
Scripts/script_commons.sh
ZcashLightClientKit.podspec

Allow this library to be added as a dependency using modular headers

Modular headers

---

ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift

Cause:
cancelAllOperations() - Canceling the operations does not automatically remove them from the queue or stop those that are currently executing. For operations that are queued and waiting for execution, the queue must still attempt to execute the operation before recognizing that it is canceled and moving it to the finished state.
logs: 
Change status form: syncing to : syncing
Change status form: syncing to : stopped
11:41:20.218 💚 DEBUG  ZcashOperation  start()  42 : <ZcashLightClientKit.CompactBlockValidationOperation: 0x7f89ad605210> started
11:41:20.218 💚 DEBUG  CompactBlockProcessor  processNewBlocks(range:)  429 : Warning: validateChainOperation operation cancelled
Change status form: stopped to : syncing
11:41:20.218 💚 DEBUG  ZcashOperation  start()  42 : …

Forcibly change the state  to stopped when the handle cancels any task in OperationQueue

---

Cargo.lock
Cargo.toml
ZcashLightClientKit.podspec
ZcashLightClientKit/Extensions/ZcashSDK+extensions.swift
ZcashLightClientKit/Stencil/ZcashSDK.stencil
ZcashLightClientKitTests/AdvancedReOrgTests.swift
rust/src/lib.rs

implement Zip 313

---

Example/ZcashLightClientSample/Podfile.lock
ZcashLightClientKit.podspec
ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
ZcashLightClientKit/Block/Processor/CompactBlockValidationInformation.swift
ZcashLightClientKit/Block/Processor/ZcashOperation.swift

Issue 240: reorg logic fails do to ARC deallocating operation

---

Example/ZcashLightClientSample/ZcashLightClientSample/SampleLogger.swift
ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
ZcashLightClientKit/Tool/DerivationTool.swift
ZcashLightClientKit/Utils/LoggingProxy.swift

changes to zealous logger + linter warnings

zealous-logger changes

---

Cargo.lock
Cargo.toml
README.md
ZcashLightClientKit/zcashlc/zcashlc.h

Some fixes and notes we accumulated while building using Rosetta 2 (Intel compatibility mode) on an m1 mac.
Addresses https://github.com/zcash/ZcashLightClientKit/issues/258

M1 build instructions

---

Cargo.lock
Cargo.toml
Example/ZcashLightClientSample/Podfile
ZcashLightClientKit/Block/Processor/CompactBlockEnhancementOperation.swift
ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
ZcashLightClientKit/Service/ProtoBuf/proto/darkside.proto
ZcashLightClientKit/Service/ProtoBuf/proto/service.proto
ZcashLightClientKit/Service/ProtoBuf/service.grpc.swift
ZcashLightClientKit/Service/ProtoBuf/service.pb.swift
ZcashLightClientKitTests/AdvancedReOrgTests.swift
ZcashLightClientKitTests/BalanceTests.swift
ZcashLightClientKitTests/proto/darkside.grpc.swift
ZcashLightClientKitTests/utils/SampleLogger.swift
rust/src/lib.rs

closes #255 
issue #261 is reproduced by causing #255 so is closed by transitivity

Outgoing transaction with no change output are not updated locally

---

ZcashLightClientKit/Block/DatabaseStorage/DatabaseMigrationManager.swift

Updating Compilation error caused by lint changes that does not show up on local builds.

shadowing confuses compiler

---

docs/testing/manual_testing/README.md

I made the manual testing steps more explicit, to handle a few corner cases I ran into when trying to follow them.

Update manual testing steps

---

Cargo.lock
Cargo.toml
Example/ZcashLightClientSample/Podfile
Example/ZcashLightClientSample/Podfile.lock
Scripts/build_librustzcash_xcode.sh
Scripts/travis/rust_setup.sh
ZcashLightClientKit/zcashlc/zcashlc.h
rust/src/lib.rs

Closes #331 
Closes Update to MnemonicSwift 2.1.0 #334
Steps:
- checkout the referenced fork, 
- push that branch into librustzcash as `autoshielding-poc-sdk-dnm`
- reference that branch
- commit 
Once this is reviewed and approved a new version of the sdk will have to be released 
each pass._

Fix Issue #331 Reference librustzcash from a branch on that repo

---

.github/workflows/swift.yml
README.md
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
ZcashLightClientKit.podspec
changelog.md

BlockProgress struct was missing a public initializer for ECC Wallet's CombineSynchronizer to convert SyncStatus into CombineSynchronizer States.
there was an internal helper but it was not exposed.  A static property was made public instead 

Expose property nullProgress for ECC Reference Wallet

---

CONTRIBUTING.md

Closes #351
In order to make the repo's history consistent going forwards,
I've added some commit message guidelines.
The core of the suggestions were taken from this article:
https://cbea.ms/git-commit/#why-not-how
The main idea is that the repo is the source of truth and helps
both readers and maintainers to understand it better.
The rationale behind the title structure is that a clean
changelog can be manufacture by running `git log --oneline`
and a little bit of editing.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review …

[#351] Write a Commit message Section for CONTRIBUTING.md

---

CONTRIBUTING.md

add a link to "Commit Messages" to the "Topics" section

[#351] add "Commit Messages" link to "topics"

---

Package.resolved
Package.swift
Sources/ZcashLightClientKit/Service/ProtoBuf/compact_formats.pb.swift
Sources/ZcashLightClientKit/Service/ProtoBuf/service.pb.swift
Tests/TestUtils/proto/darkside.pb.swift
ZcashLightClientKit.podspec

closes #394
This commit updates the generated files with the latest plugins released
along this version of the GRPC library.
`pod lib lint --verbose --allow-warnings` passed

[#394] Update swift-grpc to 1.8.0

---

Package.resolved
Package.swift
ZcashLightClientKit.podspec

[#363] bump iOS minimum deployment target to iOS 13.0

---

ZcashLightClientKit.podspec
changelog.md

[#400] Changelog for 0.15.0-beta. Podspec version

---

Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Tests/TestUtils/Tests+Utils.swift

Closes #404
This commit updates LightWalletGRPCService conform to latest
Swift-GRPC recommendations on how to set Connections KeepAlive
parameters.
See https://github.com/grpc/grpc-swift/blob/main/docs/keepalive.md

[#404] Configure GRPC KeepAlive according to docs

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Constants/Checkpoint+Constants.swift
Sources/ZcashLightClientKit/Constants/Checkpoint+mainnet.swift
Sources/ZcashLightClientKit/Constants/Checkpoint+testnet.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Model/Checkpoint.swift
Sources/ZcashLightClientKit/Model/WalletTypes.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/ReOrgTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockScanOperationTests.swift
Tests/OfflineTests/BirthdayTests.swift
Tests/OfflineTests/WalletTests.swift
Tests/TestUtils/TestCoordinator.swift

This commit makes Renames `WalletBirthday` to `Checkpoint` and
makes Checkpoint an internal type. Public ocurrences of this
type is replaced by `BlockHeight` (Int) and then retrieval of the
Checkpoint is deferred to the appropiate place in the code

[#398] Make WalletBirthday an internal type

---

Sources/ZcashLightClientKit/Extensions/SynchronizerError+LocalizedError.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Tests/OfflineTests/ErrorLocalizationTests.swift

Closes #392
This commit localizes SynchronizerError to better support Error messages

[#392] Synchronizer error 8. when syncing.

---

ZcashLightClientKit.podspec
changelog.md

Closes #403
Renames changelog.md to CHANGELOG.md

[#403] Release 0.16.0-beta

---

Package.resolved

[#416] Update GRPC to 1.8.2

---

Sources/ZcashLightClientKit/Model/Zatoshi.swift

Closes #422
This helps Secant iOS compile since it relies on these APIs that were
once internal to the app module

- [#422] Make Zatoshi extensions of `NSDecimalNumber` public

---

Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift

Closes #419
This eliminates the keepalive settings since they seem to clash with defaults
on ligthwalletd and the client gets rejected earlier than needed.

- [#419] Fix Unavailable Transport 14 when attempting to sync

---

ZcashLightClientKit.podspec
changelog.md

Closes #425
Changelog and podspect changes

[#425] release 0.16.1-beta

---

Sources/ZcashLightClientKit/Model/WalletTypes.swift
Sources/ZcashLightClientKit/Model/Zatoshi.swift

Closes #428}
Helpers that were internal to Secant now are missing when we moved them to ZcashLightClientKit. This commit fixes that
Also an Equatable WalletBalance is needed for TCA to use it in actions and stores

[#428] make some helpers publicly accessible

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanningOperation.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift

this commit splits the batch sizes so that wallets can be tweaked to either scan or download more or less blocks depending of the CompactBlockProcessor.Config used. Defaults are provided
This also bumps up the default time out for GRPC services to 30 seconds to unary calls and 100 seconds to streaming calls
Also, adds some documentation formatting that won't hurt

[#440] Split constants for Download Batches and Scanning Batches

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownloadOperation.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/NetworkTests/BlockScanOperationTests.swift
Tests/NetworkTests/BlockStreamingTest.swift

This commit implements a small buffer for the stream download operation
so it does not store a block at a time and does it in batches instead.
Closes #449

[#449] Use CompactBlock Streamer download instead of batch downloads

---

Sources/ZcashLightClientKit/Block/DatabaseStorage/CompactBlockStorage.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/DAO/PagedTransactionDao.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift

Closes #455
this reverts queue priority changes from commit `a5d0e447748257d2af5c9101391dd05a5ce929a2` since we detected it might prevent downloads to be scheduled in a
timely fashion

[#455] revert queue priority downgrade changes from [#435]

---

.github/workflows/swift.yml
.travis.yml

Closes #496 
- travis.yml updated to xcode13.4
- github actions updated to run on macos 12

[496] Travis CI and GA update to support compiler >= 5.6

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift

Closes #475 
- refactored to await/async

[475] NextStateHelper to async/await

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Base.lproj/Main.storyboard
Example/ZcashLightClientSample/ZcashLightClientSample/Derivation Tool/DerivationToolViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Get Address/GetAddressViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Package.resolved
Package.swift
Sources/ZcashLightClientKit/Block/DatabaseStorage/DatabaseMigrationManager.swift
Sources/ZcashLightClientKit/Entity/AccountEntity.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockScanOperationTests.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/NetworkTests/ZcashRustBackendTests.swift
Tests/OfflineTests/WalletTests.swift
Tests/TestUtils/Stubs.swift
Tests/TestUtils/TestCoordinator.swift

Co-authored-by: Francisco Gindre <francisco.gindre@gmail.com>

Use librustzcash migrations for the data db.

---

Package.swift

This is needed to be ablo to build on Macs without running Xcode IDE
Closes #501

[#501] Bump MacOS minimum deployment target to 10_15

---

Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Latest Block Height/LatestHeightViewController.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownloadOperation.swift
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Service/LightWalletService.swift
Sources/ZcashLightClientKit/Service/ProtoBuf/service.grpc.swift
Sources/ZcashLightClientKit/Service/ProtoBuf/service.pb.swift
Tests/NetworkTests/LightWalletServiceTests.swift
Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/FakeService.swift

Closes #463 
- migration of the protocol's methods done
- split the code so there's blocking and non-blocking API separately
- async throws unit tests added
- sample app updated to the latest API

[463] Migrate LightwalletService to Async/Await

---

Sources/ZcashLightClientKit/Block/DatabaseStorage/CompactBlockStorage.swift
Sources/ZcashLightClientKit/Block/Downloader/BlockDownloader.swift
Sources/ZcashLightClientKit/Repository/CompactBlockRepository.swift
Tests/DarksideTests/BlockDownloaderTests.swift
Tests/OfflineTests/CompactBlockStorageTests.swift
Tests/TestUtils/FakeStorage.swift
Tests/TestUtils/Stubs.swift

[464] compact block storage to async await

---

Sources/ZcashLightClientKit/Block/Downloader/BlockDownloader.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownloadOperation.swift
Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputsOperation.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/BlockDownloaderTests.swift

Closes #465 
- CompactBlockDownloading closures removed
- CompactBlockDownloading new async API provided

[465] CompactBlockDownloading to Async/Await

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownloadOperation.swift

Closes #470 
- using new sync APIs for storage and service
- whole logic wrapped in the Task
- tests passing

[470] CompactBlockStreamDownloadOperation to async

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockValidationInformation.swift

Closes #471 
- CompactBlockValidationOperation wrapped to Task

[471] CompactBlockValidationOperation to async

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancementOperation.swift

Closes #473 
- Wrapped to Task
- Downloader APIs upgraded to async one

[473] CompactBlockEnhancementOperation to async/await

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownloadOperation.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanningOperation.swift

Closes #472 
- CompactBlockBatchScanningOperation operation's main reimplemented to be Task based

[472] CompactBlockBatchScanningOperation to async

---

Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
Sources/ZcashLightClientKit/Transaction/TransactionManager.swift

Closes #483 
- protocol methods updated from closure to async APIs
- PersistentTransactionManager updated to implement async APIs
- PersistentTransactionManager deleted closure APIs
- SDKSynchronizer updated to use async APIs

[483] OutboundTransactionManager To Async/Await

---

Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/ShieldFundsTests.swift

Closes #487 
- API refactored to async
- unit tests refactored

[#487] shieldFunds to async/await

---

Example/ZcashLightClientSample/ZcashLightClientSample/Sapling Parameters/SaplingParametersViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Utils/SaplingParameterDownloader.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/NetworkUpgradeTests.swift
Tests/DarksideTests/PendingTransactionUpdatesTest.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/Z2TReceiveTests.swift

Closes #486
- sendToAddress and SaplingParameterDownloader refactored to async
- reducing number of Tasks in Sample app
- async sendToAddress unit test refactored except NetworkUpgradeTests
- NetworkUpgradeTests refactored to async API

[#486] sendToAddress async/await

---

Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift

Closes #546 
- async/await API update
- code cleaned up from the unused APIs

[#546] TransactionEncoder To Async/Await

---

Sources/ZcashLightClientKit/Block/DatabaseStorage/CompactBlockStorage.swift
Sources/ZcashLightClientKit/Block/Downloader/BlockDownloader.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Repository/CompactBlockRepository.swift
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Service/LightWalletService.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
Tests/DarksideTests/BlockDownloaderTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/LightWalletServiceTests.swift
Tests/OfflineTests/CompactBlockStorageTests.swift
Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/FakeService.swift
Tests/TestUtils/FakeStorage.swift
Tests/TestUtils/Stubs.swift
Tests/TestUtils/TestDbBuilder.swift

Closes #492 
- blocking API removed, only latestBlockHeight() stayed
- non-blocking closure based API removed
- unit tests updated to use async API

[#492] Get rid of blocking API

---

Sources/ZcashLightClientKit/Block/DatabaseStorage/CompactBlockStorage.swift
Sources/ZcashLightClientKit/Block/Downloader/BlockDownloader.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Repository/CompactBlockRepository.swift
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Service/LightWalletService.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
Tests/DarksideTests/BlockDownloaderTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/LightWalletServiceTests.swift
Tests/OfflineTests/CompactBlockStorageTests.swift
Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/FakeService.swift
Tests/TestUtils/FakeStorage.swift
Tests/TestUtils/Stubs.swift
Tests/TestUtils/TestDbBuilder.swift
Tests/TestUtils/Tests+Utils.swift

Merge master into this branch

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift

Fix compilation of sample project

---

Sources/ZcashLightClientKit/Model/WalletTypes.swift
Sources/ZcashLightClientKit/Tool/DerivationTool.swift
Tests/NetworkTests/ZcashRustBackendTests.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolMainnetTests.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolTestnetTests.swift

I found that unified viewing keys were being validated as sapling viewing keys

Fix ufvk validation

---

Package.resolved
Package.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
Sources/ZcashLightClientKit/Entity/PendingTransactionEntity.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
Tests/OfflineTests/PendingTransactionRepositoryTests.swift

Update to latest librustzcash

---

Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanning.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockValidationInformation.swift
Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
Sources/ZcashLightClientKit/Block/Utils/NotificationCenter+Post.swift
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/ShieldFundsTests.swift
Tests/DarksideTests/SynchronizerTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/OfflineTests/WalletTests.swift
Tests/TestUtils/FakeService.swift
Tests/TestUtils/TestCoordinator.swift

Closes #523 
- Sample app refactored for the processor being an actor
- tests refactored as well
- dark side tests fixed
- code cleanup
- review of the code and last touches

[#523] Make a CompactBlockProcessor an Actor

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift

[#581] getTransparentBalanceForAccount error not handled

---

.travis.yml

Closes #595 
- yml file updated to the latest Xcode

[#595] Update Travis to use Xcode 14

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift

Closes #579
This is what happens when database was locked:
- App is syncing.
- While rustBackend.scanBlocks(…) is in progress app goes to background. Background task is launched and ECC works for some time in background.
- When background task is finished synchronizer.stop() is called.
- Inside CompactBlockProcessor.stop()is called. In this method cancelableTask is canceled and state is set to stopped no matter what. And this is the problem. Because even when canceled is called rust scanning isn’t canceled. But state doesn’t care about it. And next time when app is launched new synchronisation is started and now you have processing code running in two threads causing DB lock.
So I moved setting state to stopped to processNewBlocks method. It's set after the work is canceled and really …

[#579] Fix database lock

---

Package.swift
ZcashLightClientKit.podspec
changelog.md

Release 0.17.0-alpha.2

---

Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Sources/ZcashLightClientKit/Block/DatabaseStorage/CompactBlockStorage.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanning.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockValidationInformation.swift
Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift
Sources/ZcashLightClientKit/DAO/CompactBlockDAO.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/TestUtils/TestCoordinator.swift

- Implements parallel downloading, validating and scanning of blocks.
- For now code makes sure that scanning is made in order. There is no support for full parallelisation in rust API yet.
- For now block processor downloads 100 blocks and then validate them and scanned them. Thanks to this not a lof of disk space is required for synchronisation.
- Most of the work is done in `CompactBlockProcessor.processNewBlocks(...)`.
- Progress reporting of `CompactBlockProcessor` is update so it works with new approach.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see …

[#566] Parallel block processing

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

Fix Package.resolved file for Sample SDK app

---

Example/ZcashLightClientSample/ZcashLightClientSample/Get Address/GetAddressViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift

Fix Sample SDK app compilation

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
ZcashLightClientKit.podspec

point to libzcashlc 0.1.0-beta.2

0.17.0-alpha.4

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Utils/ResourcesUsageChecker.swift

Closes #570
Added small utility which can be easily used to measure how much resources some feature uses.

[#570] Add resources usage checker

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/FigureNextBatch.swift

Closes #619
- When computing next action in `NextStateHelper.nextStateAsync` now scanning state is also taken into consideration.
- When processing blocks download phase is skipped when it's detected that everything is already downloaded.

[#619] Correctly resume syncing process in scanning phase

---

.travis.yml
Package.resolved
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/FigureNextBatch.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift

[#614] make prepare(with:) and get{pool_type}Address() synchronous

---

Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/SychronizerDarksideTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift
Tests/OfflineTests/PagedTransactionRepositoryTests.swift
Tests/TestUtils/MockTransactionRepository.swift

state for this synchronizer.
also reports the SynchronizerState on synchronizerStarted notification.

[#621] Adds a synchronizer state subject with the last available

---

Package.resolved
Package.swift

[#597] Bump up SQLite Swift to 0.14.1

---

Sources/ZcashLightClientKit/Model/Memo.swift
Tests/OfflineTests/Zip302MemoTests.swift

This provides a method for clients to handle UI for text memo limit correctly handling memos that are visibly fit within the capacity defined in ZIP-302 but when encoded into UTF-8 bytes their size exceeds such limit.
Closes #639

[#639] Provide an API to estimate TextMemo length limit correctly

---

Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift

It's not good practice to make internal combine subjects accessible from outside of SDK. So `lastState` is changed from `CurrentValueSubject` to `Publisher`. This doesn't have any effect on public API. It just makes SDK safer.

Change lastState property to Publisher from Subject in SDKSynchronizer

---

Sources/ZcashLightClientKit/Utils/SaplingParameterDownloader.swift

Closes #631 
- Verification of the SHA1 after downloading the file(s)
- Public API for the checking the validation of the sapling params files
- Private API is encapsulated in private extension

[#631] Verify SHA1 correctness of Sapling files after downloading

---

Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
Sources/ZcashLightClientKit/Block/Processor/HandleSaplingParametersIfNeeded.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Providers/ResourceProvider.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Utils/SaplingParameterDownloader.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift
Tests/TestUtils/TestCoordinator.swift

Closes #637 
Closes #633 
- sync process enhanced to try to download sapling params if needed
- tests fixed

[#637] Make sapling parameter download part of processing blocks

---

Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/DarksideSanityCheckTests.swift
Tests/DarksideTests/PendingTransactionUpdatesTest.swift
Tests/DarksideTests/ReOrgTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/ShieldFundsTests.swift
Tests/DarksideTests/SychronizerDarksideTests.swift
Tests/DarksideTests/SynchronizerTests.swift
Tests/DarksideTests/Z2TReceiveTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift
Tests/OfflineTests/WalletTests.swift
Tests/TestUtils/TestCoordinator.swift

- TestCoordinator doesn't need to be used in async manner.

Cleanup warnings

---

Tests/DarksideTests/RewindRescanTests.swift
Tests/TestUtils/TestCoordinator.swift

Closes #585 
- test fixed, the saplingActivation wasn't passed to the block processor just like to the service, there's the mismatch

[#585] Fix RewindRescanTests

---

Package.resolved
Package.swift
Tests/DarksideTests/ShieldFundsTests.swift

This commit adopts libzcashlc 0.1.1 which fixes this error
Closes #665

[#665] Fix testShieldFunds() `get_transparent_balance` error

---

CHANGELOG.md
ZcashLightClientKit.podspec

updates `libzcashlc` to `0.1.1` to fix an error where getting a transparent balance on an empty database would fail.
closes #675

[#675] release 0.17.4-beta

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Tests/TestUtils/MockTransactionRepository.swift
ZcashLightClientKit.podspec

- Structures that represent transactions DB views are newly define.
- New structures are:
- `TransactionNG.Overview`
- `TransactionNG.Received`
- `TransactionNG.Sent`
- `TransactionNG` is used as temporary name. `Transaction` is existing structure in the code. `TransactionNG` will be eventually renamed to `Transaction` once current `Transaction` is removed from code.
- New methods that are using new structures are added to `TransactionRepository`. Those are slightly changed compared to predecessors. Those are now little bit simpler to use.
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think …

[#556] Define structures for db view and add new repository methods

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
Tests/OfflineTests/TransactionRepositoryTests.swift

[#556] Replace TransactionRepository.findBy methods with new transaction methods

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/ZcashLightClientKit/Block/Downloader/BlockDownloader.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Extensions/SynchronizerError+LocalizedError.swift
Sources/ZcashLightClientKit/Repository/CompactBlockRepository.swift
Sources/ZcashLightClientKit/Repository/PendingTransactionRepository.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
Sources/ZcashLightClientKit/Transaction/TransactionManager.swift
Tests/DarksideTests/SychronizerDarksideTests.swift
Tests/TestUtils/FakeStorage.swift
Tests/TestUtils/MockTransactionRepository.swift

Closes #677
- Previously when keychain wanted to do wipe wallet had to do it on it's own. Which isn't good. Now wallet can simply call `synchronizer.wipe()` and it's done.
- This change brings support for wipe. `Synchronizer` has new method `wipe()` which takes care of everything. All the database connections are closed. Databases are removed. `InternalSyncProgress` is reset.

[#677] Add support for wipe into SDK

---

Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Tests/TestUtils/MockTransactionRepository.swift

[#556] Remove unused TransactionRepository.findEncodedTransactionBy method

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample/Base.lproj/Main.storyboard
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Package.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockDownload.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanning.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockValidationInformation.swift
Sources/ZcashLightClientKit/Block/Processor/FetchUnspentTxOutputs.swift
Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/PerformanceTests/SDKMetricsTests.swift
Tests/PerformanceTests/SynchronizerTests.swift
docs/testing/Performance.md

- Merge master to 657_download_change branch.
- Changed how analytics are used when downloading and scanning blocks. 

[#657] Merge branch 'master' into 657_download_change

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/xcshareddata/xcschemes/All.xcscheme

This is small improvement of lives for developers. Before this change if developer wanted to test if change can be compiled then developer had to go scheme by scheme and test compilation. This change introduces `All` scheme which builds all the targets on one key stroke/mouse click.

Add Xcode scheme that builds all the targets

---

Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift
Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
Tests/DarksideTests/AdvancedReOrgTests.swift

There can be stored transactions with expiryHeight and raw set to NULL in database. So these two properties must be optional in code.

[#556] Make expiryHeight and raw optional

---

Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockScanning.swift

[#657] Scan batch size is computed for each scan loop

---

Example/ZcashLightClientSample/ZcashLightClientSample/Paginated Transactions/PaginatedTransactionsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift
Sources/ZcashLightClientKit/Block/Downloader/BlockDownloader.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/DAO/PagedTransactionDao.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Entity/PendingTransactionEntity.swift
Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
Sources/ZcashLightClientKit/Repository/PaginatedTransactionRepository.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Service/LightWalletService.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift
Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/SychronizerDarksideTests.swift
Tests/OfflineTests/TransactionRepositoryTests.swift
Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/FakeService.swift
Tests/TestUtils/MockTransactionRepository.swift

This change is really only replace one string with other. No logic was changed.

[#556] Rename Transaction to TransactionNG

---

Example/ZcashLightClientSample/ZcashLightClientSample/List Transactions/TransactionsDataSource.swift
Example/ZcashLightClientSample/ZcashLightClientSample/List Transactions/TransactionsTableViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Paginated Transactions/PaginatedTransactionsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Model/Memo.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/OfflineTests/MemoTests.swift
Tests/TestUtils/MockTransactionRepository.swift

[#683] Add Synchronizer API to fetch memos for transactions

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/NetworkTests/CompactBlockReorgTests.swift

Closes #671 
- sdk and demo app modified

[#671] Make CompactBlockProcessor Internal

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift

[#728] Remove Swiftilint SPM package plugin

---

.swiftlint.yml

This adds the `included` rule to specify which folders to lint Closes #730

[#730] Swiftlint picks the wrong files

---

Example/ZcashLightClientSample/ZcashLightClientSample/Paginated Transactions/PaginatedTransactionsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift
Sources/ZcashLightClientKit/Block/Downloader/BlockDownloader.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockEnhancement.swift
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/DAO/PagedTransactionDao.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Entity/PendingTransactionEntity.swift
Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
Sources/ZcashLightClientKit/Repository/PaginatedTransactionRepository.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Sources/ZcashLightClientKit/Service/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Service/LightWalletService.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/SychronizerDarksideTests.swift
Tests/OfflineTests/TransactionRepositoryTests.swift
Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/FakeService.swift
Tests/TestUtils/MockTransactionRepository.swift

- Xcode's refactor feature used. Only renamed happened no logic was changed.

[#556] Rename Transaction to ZCashTransaction

---

CHANGELOG.md

- Added changelog for #556.
- Update formatting so changelog is easier to read when it's rendered.

[#556] Add changelog

---

CHANGELOG.md
Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift

This fixes an issue where the default reorg was 20 blocks rewind instead of 10. The reorg count was incremented before calling the rewind height computing function.
Closes #645

[#645] Default rewind after ReOrg is 20 blocks when it should be 10

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.pbxproj
Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Tests/DarksideTests/ShieldFundsTests.swift
Tests/TestUtils/MockTransactionRepository.swift
Tests/TestUtils/Stubs.swift

- Swiftlint binary is included in the repository.
- Fixed few swiftlint warnings

[#735] Use Swiftlint for the SDK

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/SaplingParameters/SaplingParametersHandler.swift

Closes #745
- Added `SaplingParametersHandler` protocol and `SaplingParametersHandlerImpl` struct.

[#745] Refactor sapling parameters handling code in CompactBlockProcessor

---

Sources/ZcashLightClientKit/Block/FilesystemStorage/FSCompactBlockRepository.swift
Sources/ZcashLightClientKit/Initializer.swift
Tests/DarksideTests/BlockDownloaderTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/NetworkTests/DownloadTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift
Tests/OfflineTests/CompactBlockProcessorOfflineTests.swift
Tests/OfflineTests/CompactBlockRepositoryTests.swift
Tests/OfflineTests/FsBlockStorageTests.swift
Tests/TestUtils/TestCoordinator.swift

Closes #771
- Renamed `cacheDirectory` param in `FSCompactBlockRepository` constructor to `fsBlockDbRoot`.
- Pass same paths to `FSCompactBlockRepository` and `FSMetadataStore` from tests.

[#771] Fix tests failing because of different paths passed to `FSCompactBlockRepository` and `FSMetadataStore`

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Sources/ZcashLightClientKit/Modules/Service/GRPC/ProtoBuf/service.grpc.swift
Tests/DarksideTests/AdvancedReOrgTests.swift

[#770] Update GRPC swift library

---

Tests/TestUtils/TestCoordinator.swift

[#713] Remove unused methods from TestCoordinator

---

Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/DarksideSanityCheckTests.swift
Tests/DarksideTests/InternalStateConsistencyTests.swift
Tests/DarksideTests/PendingTransactionUpdatesTest.swift
Tests/DarksideTests/ReOrgTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/ShieldFundsTests.swift
Tests/DarksideTests/SychronizerDarksideTests.swift
Tests/DarksideTests/SynchronizerTests.swift
Tests/DarksideTests/Z2TReceiveTests.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolMainnetTests.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolTestnetTests.swift
Tests/TestUtils/Tests+Utils.swift

[#715] Move seed phrase from specific tests to Environment

---

Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/BlockDownloaderTests.swift
Tests/DarksideTests/RewindRescanTests.swift

[#780] Disable tests that aren't currently working

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/BlockDownloaderTests.swift
Tests/DarksideTests/DarksideSanityCheckTests.swift
Tests/DarksideTests/InternalStateConsistencyTests.swift
Tests/DarksideTests/PendingTransactionUpdatesTest.swift
Tests/DarksideTests/ReOrgTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/ShieldFundsTests.swift
Tests/DarksideTests/SychronizerDarksideTests.swift
Tests/DarksideTests/SynchronizerTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/DarksideTests/Z2TReceiveTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/NetworkTests/LightWalletServiceTests.swift
Tests/OfflineTests/InternalSyncProgressTests.swift
Tests/OfflineTests/PagedTransactionRepositoryTests.swift
Tests/OfflineTests/PendingTransactionRepositoryTests.swift
Tests/OfflineTests/RawTransactionTests.swift

[#796] Fix tests

---

Tests/DarksideTests/BlockDownloaderTests.swift

[#788] Fix testSmallDownloadAsync test

---

CHANGELOG.md
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/SynchronizerTests.swift

[#793] Send synchronizerStopped notification only when sync process stops

---

Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift
Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
Tests/DarksideTests/BalanceTests.swift

[#784] Fix testVerifyBalanceAfterExpiredTransaction test

---

Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift

[#803] Fix how transaction value is showed in the SDK sample app

---

Tests/DarksideTests/AdvancedReOrgTests.swift

- Test works with currently used lightwalletd. It doesn't work with newer. It can be enabled for now.

[#644] Enable test testReOrgRemovesIncomingTxForever

---

Tests/DarksideTests/RewindRescanTests.swift

[#789] Fix testRescanToHeight test

---

Sources/ZcashLightClientKit/Utils/OSLogger.swift

- This is necessary to finish https://github.com/zcash/secant-ios-wallet/issues/529. The Secant has special log method for logging tca stuff. And this method will be in extension of `OSLogger` and it needs to access `oslog`.

Set oslog inside OSLogger public for read

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.pbxproj

Remove linter binary from repository

---

CHANGELOG.md
Package.resolved
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift

contains no public API changes.
Adds `func shouldClearBlockCacheAndUpdateInternalState() -> BlockHeight?` to `SyncRanges` so that the compact block processor can advert internal states that are not consistent and recover from such state.
Closes #821

[#821] `failedToWriteMetadata` at sync startup

---

Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/DAO/PagedTransactionDao.swift
Sources/ZcashLightClientKit/DAO/PendingTransactionDao.swift
Sources/ZcashLightClientKit/Entity/SentNoteEntity.swift
Sources/ZcashLightClientKit/Modules/Service/GRPC/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Modules/Service/GRPC/ProtoBuf/Extensions/Protocolbuffer+Extensions.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Utils/SaplingParameterDownloader.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/RewindRescanTests.swift

[#818] Swift 5.7 syntax update

---

Sources/ZcashLightClientKit/Block/SaplingParameters/SaplingParametersHandler.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift

Closes #832 
- fixed copy paste bug
- fixed params not being downloaded when transparent funds available

[#832] Check for missing spending and output params is not full

---

Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
Tests/TestUtils/AlternativeSynchronizerAPITestsData.swift
Tests/TestUtils/SynchronizerMock.swift
Tests/TestUtils/UnspentTransactionOutputEntityMock.swift

- Added tests are testing in general if the `ClosuresSDKSynchronizer` is correctly calling `Synchronizer` and if the values are correctly returned.
- `ClosuresSDKSynchronizer` doesn't contain any logic but it is public API and we should be sure that it works correctly.

[#831] Add tests for ClosureSDKSynchronizer

---

Sources/ZcashLightClientKit/Utils/SaplingParameterDownloader.swift
Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
Tests/TestUtils/SynchronizerMock.swift

[#831] Add tests for CombineSDKSynchronizer

---

CHANGELOG.md

[#831] Add changelog

---

Sources/ZcashLightClientKit/Initializer.swift
Tests/PerformanceTests/SynchronizerTests.swift
Tests/TestUtils/TestCoordinator.swift

[#845] Introduce ZcashSynchronizerAlias enum

---

Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift

[#852] SDKSynchronizer using queues label based on the alias

---

Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Modules/Service/GRPC/LightWalletGRPCService.swift
Sources/ZcashLightClientKit/Modules/Service/LightWalletService.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/BlockDownloaderTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/NetworkTests/DownloadTests.swift
Tests/NetworkTests/LightWalletServiceTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift
Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
Tests/OfflineTests/CompactBlockProcessorOfflineTests.swift
Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/FakeService.swift
Tests/TestUtils/TestCoordinator.swift

[#850] Remove synchronizerConnectionStateChanged notification

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
Tests/DarksideTests/InternalStateConsistencyTests.swift
Tests/DarksideTests/SynchronizerTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift
Tests/OfflineTests/InternalSyncProgressTests.swift
Tests/PerformanceTests/SynchronizerTests.swift
Tests/TestUtils/Stubs.swift
Tests/TestUtils/TestCoordinator.swift

[#849] Make InternalSyncProgress aware of the Alias

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Tests/OfflineTests/FsBlockStorageTests.swift

[#853] Only instance with default Alias migrates legacy cache DB

---

Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift
Sources/ZcashLightClientKit/Block/Enhance/BlockEnhancer.swift
Sources/ZcashLightClientKit/Block/FetchUnspentTxOutputs/UTXOFetcher.swift
Sources/ZcashLightClientKit/Block/Scan/BlockScanner.swift
Sources/ZcashLightClientKit/Block/Validate/BlockValidator.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/NetworkTests/DownloadTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift
Tests/OfflineTests/CompactBlockProcessorOfflineTests.swift
Tests/OfflineTests/FsBlockStorageTests.swift
Tests/PerformanceTests/SDKMetricsTests.swift
Tests/PerformanceTests/SynchronizerTests.swift
Tests/TestUtils/SynchronizerMock.swift

Closes #846 
- metrics are not longer a singleton
- tests fixed

[#846] Stop using SDKMetrics as singleton

---

CHANGELOG.md

- Add changelog for #209.
- Overall improve readability of the rendered changelog. Tickets references are now prefixed with `###` instead of `- `.

[#209] Add changelog

---

Sources/ZcashLightClientKit/DAO/TransactionDao.swift

[#883] Use async in TransactionSQLDAO

---

CHANGELOG.md
Sources/ZcashLightClientKit/ClosureSynchronizer.swift
Sources/ZcashLightClientKit/CombineSynchronizer.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/ClosureSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/CombineSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
Tests/TestUtils/Stubs.swift
Tests/TestUtils/SynchronizerMock.swift

Closes #880 
This makes deprecations marked long ago effective.
This leaves out anything FsBlockDb related.

Make some deprecations effective

---

Sources/ZcashLightClientKit/DAO/UnspentTransactionOutputDao.swift
Sources/ZcashLightClientKit/Repository/UnspentTransactionOutputRepository.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift

[#878] UnspentTransactionOutputRepository to async

---

.github/workflows/code_ql.yml

This is a PR that sets us into the beta for CodeQL 🎉

CodeQL Beta 👀

---

.github/workflows/code_ql.yml

[#889] fix branches that will be built with CodeQL

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift

- Fixed the guard with explicit self

[#896] Fix SDK compilation fail caused by Swift 5.8

---

.swiftlint.yml
.swiftlint_tests.yml
Tests/DarksideTests/BlockDownloaderTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/PerformanceTests/SynchronizerTests.swift
Tests/TestUtils/Stubs.swift

[#888] Fix Darkside tests

---

Tests/DarksideTests/BlockDownloaderTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/NetworkTests/DownloadTests.swift
Tests/OfflineTests/BlockBatchValidationTests.swift
Tests/OfflineTests/CompactBlockProcessorOfflineTests.swift
Tests/OfflineTests/CompactBlockRepositoryTests.swift
Tests/OfflineTests/FsBlockStorageTests.swift
Tests/OfflineTests/NotesRepositoryTests.swift
Tests/OfflineTests/NullBytesTests.swift
Tests/OfflineTests/TransactionRepositoryTests.swift
Tests/OfflineTests/WalletTests.swift
Tests/OfflineTests/ZcashRustBackendTests.swift
Tests/PerformanceTests/SynchronizerTests.swift
Tests/TestUtils/Tests+Utils.swift

I broke the tests because I moved `testTempDirectory` from each `TestCase` to the `Environment`. By this I caused that each tests uses exactly same URL. Which is directly against purpose of `testTempDirectory`.
So now each test calls this one and store it to local variable. So each test has unique URL.

[#888] Fix potentially broken tests

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/TestUtils/Sourcery/AutoMockable.stencil
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Sourcery/generateMocks.sh
Tests/TestUtils/Stubs.swift

`ZcashRustBackendWelding.rustBackend.consensusBranchIdFor(height:)` can now be nonisolated because it's possible to generate mocks for nonisolated methods.
The code which mocks `ZcashRustBackendWelding` in tests is changed bit also. Not it doesn't need to access `self` from closures in most of the cases. But it's just syntax. Logic stayed the same.

[#888] Add ability to mock nonisolated methods to AutoMockable.stencil

---

CHANGELOG.md
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift

[#888] Add changelog and fix the documentation in ZcashRustBackendWelding

---

Sources/ZcashLightClientKit/Model/WalletTypes.swift
Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Tool/DerivationTool.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolMainnetTests.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolTestnetTests.swift
Tests/OfflineTests/RecipientTests.swift
Tests/OfflineTests/UnifiedTypecodesTests.swift
Tests/OfflineTests/ZcashRustBackendTests.swift
Tests/TestUtils/TestsData.swift

- Renamed `ZcashKeyDeriving` to `ZcashKeyDerivationBackendWelding`. So the naming scheme is same as for `ZcashRustBackendWelding`.
- `ZcashKeyDerivationBackend` is now struct instead of enum.
- Methods in `ZcashKeyDerivationBackendWelding` (except one) are no longer static. Because of this the respective methods in `DerivationTool` aren't also static anymore.

[#888] Rename derivation rust backend protocol and remove static methods

---

Tests/DarksideTests/SynchronizerDarksideTests.swift

Fix SynchronizerDarksideTests

---

Sources/ZcashLightClientKit/Block/DatabaseStorage/DatabaseMigrationManager.swift
Sources/ZcashLightClientKit/Block/DatabaseStorage/DatabaseStorageError.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Tests/TestUtils/TestDbBuilder.swift

[#922] Update error handling in DatabaseMigrationManager.swift

---

Sources/ZcashLightClientKit/Error/Sourcery/ZcashError.stencil
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Utils/SaplingParameterDownloader.swift

[#955] Update error handling in SaplingParameterDownloader

---

Sources/ZcashLightClientKit/DAO/NotesDao.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift

[#936] Update error handling in NotesDao

---

Sources/ZcashLightClientKit/DAO/BlockDao.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift

[#935] Update error handling in BlockDao

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift
Tests/OfflineTests/InternalSyncProgressTests.swift

[#931] InternalSyncProgress.computeNextState doesn't need to throw

---

Sources/ZcashLightClientKit/Block/FilesystemStorage/FSCompactBlockRepository.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Repository/CompactBlockRepository.swift
Sources/ZcashLightClientKit/Tool/DerivationTool.swift
Tests/OfflineTests/FsBlockStorageTests.swift

[#928] Update error handling in FSCompactBlockRepository

---

Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift

Closes #942 
- ZcashTransaction init errors converted to the ZcashError

[#942] Update error handling in TransactionEntity

---

Sources/ZcashLightClientKit/Block/Enhance/BlockEnhancer.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Tests/TestUtils/MockTransactionRepository.swift

Closes #939 
- TransactionRepositoryError removed and replaced with ZcashError

[#939] Update error handling in TransactionDao

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift

Closes #969.
I am not sure if I can image all the cases that can be affected by this change. By I did some testing and sync in the app works. Tests are ok. And new function is called in few tests. So we should be ok here.

[#969] Clear blocks cache when error occurs

---

Sources/ZcashLightClientKit/Entity/ZcashCompactBlock.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Utils/SaplingParameterDownloader.swift

[#943] Update error handling in ZcashCompactBlock

---

Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Model/Memo.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/OfflineTests/Zip302MemoTests.swift

Closes #945
Also fixes `testStreamTimeout` test.

[#945] Update error handling in Memo

---

Sources/ZcashLightClientKit/Constants/Checkpoint+Constants.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Model/Checkpoint.swift

[#934] Update error handling in Checkpoint

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Validate/BlockValidator.swift

[#932] Update error handling in BlockValidator

---

Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift

[#954] Update error handling in WalletTransactionEncoder

---

Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Transaction/PersistentTransactionManager.swift

[#953] Update error handling in PersistentTransactionManager

---

Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/OfflineTests/InitializerOfflineTests.swift
Tests/OfflineTests/SynchronizerOfflineTests.swift

[#956] Update error handling in Initializer

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Model/Zatoshi.swift

Closes #947 
- Zatoshi's errors converted to ZcashError

[#947] Update error handling in Zatoshi

---

Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksListViewController.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Tool/DerivationTool.swift
Tests/DarksideTests/PendingTransactionUpdatesTest.swift
Tests/OfflineTests/SynchronizerOfflineTests.swift
Tests/TestUtils/TestCoordinator.swift
Tests/TestUtils/TestsData.swift

DerivationTool.init should be public. This was removed by accident when adopting async.

Make DerivationTool constructor public

---

Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/TestUtils/TestCoordinator.swift

Fixes nonce paramenter in darkside api. also corrects tests block staging for the failing tests
closes #644

[#644] AdvancedReOrg Tests fails when running Lightwalletd on `master`

---

Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksListViewController.swift
Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
Sources/ZcashLightClientKit/Tool/DerivationTool.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolMainnetTests.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolTestnetTests.swift
Tests/OfflineTests/SynchronizerOfflineTests.swift
Tests/OfflineTests/WalletTests.swift
Tests/PerformanceTests/SynchronizerTests.swift
Tests/TestUtils/TestCoordinator.swift
Tests/TestUtils/TestsData.swift

It looks like that some methods in `ZcashKeyDerivationBackendWelding` were left async by mistake. There is no reason for any method there to be async.
After this change no method in `DerivationTool` has to async. It makes things much easier.

Make all methods in ZcashKeyDerivationBackendWelding non async

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/ZcashLightClientKit/Block/Scan/BlockScanner.swift

this bumps up the amount of blocks to scan on sections of the chain that have full blocks
Closes #1017

[#1017] Tweak batch size and scan height

---

CHANGELOG.md
Sources/ZcashLightClientKit/Model/Memo.swift

Changes the way unpadded bytes are turned into a UTF-8 Swift String without using cString assuming APIs that would overflow memory and add garbled trailing bytes.
Closes #1019
add changelog entry

[#1019] Memo has trailing garbled text

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Synchronizer/Dependencies.swift
Tests/AliasDarksideTests/SDKSynchronizerAliasDarksideTests.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/DarksideSanityCheckTests.swift
Tests/DarksideTests/InternalStateConsistencyTests.swift
Tests/DarksideTests/PendingTransactionUpdatesTest.swift
Tests/DarksideTests/ReOrgTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/ShieldFundsTests.swift
Tests/DarksideTests/SynchronizerDarksideTests.swift
Tests/DarksideTests/SynchronizerTests.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/DarksideTests/Z2TReceiveTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/NetworkTests/DownloadTests.swift

Closes #1025 
- CompactBlockProcessor updated to use DI

[#1012] Introduce dependency injection

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/PendingTransactionUpdatesTest.swift
Tests/DarksideTests/SynchronizerDarksideTests.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift

- Call `setSyncRange()` in tests.
- Little update to `BlockDownloader` API so it makes more sense.

Fix tests related to blocks downloading

---

Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift

`lastError` inside the `BlockDownloaderImpl` was set even when downloading task was canceled. And because it was canceled the `lastError` has never been read by CBP before the next sync. And when next sync was started it was immediately failed because of cancelation error stored in `lastError`.

Fix error handling in BlockDownloaderImpl

---

Sources/ZcashLightClientKit/Block/Actions/Action.swift
Sources/ZcashLightClientKit/Block/Actions/ChecksBeforeSyncAction.swift
Sources/ZcashLightClientKit/Block/Actions/ClearAlreadyScannedBlocksAction.swift
Sources/ZcashLightClientKit/Block/Actions/ClearCacheAction.swift
Sources/ZcashLightClientKit/Block/Actions/ComputeSyncRangesAction.swift
Sources/ZcashLightClientKit/Block/Actions/DownloadAction.swift
Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift
Sources/ZcashLightClientKit/Block/Actions/FetchUTXOsAction.swift
Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Block/Actions/ScandownloadedButUnscannedAction.swift
Sources/ZcashLightClientKit/Block/Actions/ValidateAction.swift
Sources/ZcashLightClientKit/Block/Actions/ValidateServerAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift
Sources/ZcashLightClientKit/Block/Utils/InternalSyncProgress.swift

- For now I created `CompactBlockProcessorNG` where I started with implementation of the state machine. I did it to not break the rest of the SDK. This change will be merged to the feature branch. And before it is merged to `main` branch code from `CompactBlockProcessorNG` will be moved to `CompactBlockProcessor`.
- The new code is not used. It just shows and explains how it is done. It is proof of concept.
- I did put either commented current code or comment to some places to explain what should be done there.
- New important data types:
- `ActionContext` is context that can hold any data that needs to be shared between actions. For example sync ranges or current state.
- `CBPState` is state of the `CompactBlockProcessor`. Each state is handled by one action. This doesn't apply to …

[#700] CompactBlockProcessor as state machine proof of concept

---

Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Extensions/Error+ZcashError.swift

Closes #1035 
- new ZcashError.unknown that wraps and handles any Error added

[#1035] Create ZcashError.unknown

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1054] Add config to state machine CBP

---

Sources/ZcashLightClientKit/Block/Actions/DownloadAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift
Sources/ZcashLightClientKit/Block/Download/BlockDownloader.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift

[#1043] Implement DownloadAction

---

Sources/ZcashLightClientKit/Block/Actions/ValidateAction.swift

[#1049] Implement ValidateAction

---

Sources/ZcashLightClientKit/Block/Actions/ValidateServerAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1050] Implement ValidateServerAction

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1056] Add constructors to state machine CBP

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1061] Add failure methods for state machine CBP

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1055] Implement retry timer to state machine CBP

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1058] Implement stop for state machine CBP

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1052] Implement AfterSyncHooksManager when using state machine CBP

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1060] Implement wipe for state machine CBP

---

Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/OfflineTests/FsBlockStorageTests.swift

[#780] part of Adopt green policy
fixes docs and deletes fixme for [#783]
closes #783
[#785]: Fix test testSingleNoteNoChangeTransaction
Closes #785     
[#786] fix testVerifyChangeTransaction
Closes #786
[#790] mark as fixed testRewindAfterSendingTransaction    
Closes #790    
[#865] Fix test testStoringTenSandblastedBlocks
Closes #865
[#791] Fix test testRewindAfterSendingTransaction 
Closes #791    
[#783]: Fix test testMaxAmountSendBroadcast
Closes #783
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review …

Fix disabled tests

---

Sources/ZcashLightClientKit/Block/Actions/Action.swift
Sources/ZcashLightClientKit/Block/Actions/ChecksBeforeSyncAction.swift
Sources/ZcashLightClientKit/Block/Actions/ClearAlreadyScannedBlocksAction.swift
Sources/ZcashLightClientKit/Block/Actions/ClearCacheAction.swift
Sources/ZcashLightClientKit/Block/Actions/ComputeSyncRangesAction.swift
Sources/ZcashLightClientKit/Block/Actions/DownloadAction.swift
Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift
Sources/ZcashLightClientKit/Block/Actions/FetchUTXOsAction.swift
Sources/ZcashLightClientKit/Block/Actions/MigrateLegacyCacheDBAction.swift
Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Block/Actions/ScanDownloadedButUnscannedAction.swift
Sources/ZcashLightClientKit/Block/Actions/ValidateAction.swift
Sources/ZcashLightClientKit/Block/Actions/ValidateServerAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

Closes #1045 
- updated the way Actions communicate data back to the CBP
- used this mechanism to pass result of utxos fetch so it's passed to the SDKSynchronizer as an Event

[#1045] Implement FetchUTXOsAction

---

Sources/ZcashLightClientKit/Block/Actions/Action.swift
Sources/ZcashLightClientKit/Block/Actions/ComputeSyncRangesAction.swift

[#1042] Implement ComputeSyncRangesAction

---

Sources/ZcashLightClientKit/Block/Actions/Action.swift
Sources/ZcashLightClientKit/Block/Actions/ChecksBeforeSyncAction.swift
Sources/ZcashLightClientKit/Block/Actions/ClearAlreadyScannedBlocksAction.swift
Sources/ZcashLightClientKit/Block/Actions/ClearCacheAction.swift
Sources/ZcashLightClientKit/Block/Actions/ComputeSyncRangesAction.swift
Sources/ZcashLightClientKit/Block/Actions/DownloadAction.swift
Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift
Sources/ZcashLightClientKit/Block/Actions/FetchUTXOsAction.swift
Sources/ZcashLightClientKit/Block/Actions/MigrateLegacyCacheDBAction.swift
Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Block/Actions/ScanDownloadedButUnscannedAction.swift
Sources/ZcashLightClientKit/Block/Actions/ValidateAction.swift
Sources/ZcashLightClientKit/Block/Actions/ValidateServerAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#700] Implement cache clearing when some actions fail

---

Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift

Closes #1046 
- action for sapling param files finished

[#1046] implement sapling params action

---

Sources/ZcashLightClientKit/Block/Actions/ComputeSyncRangesAction.swift
Sources/ZcashLightClientKit/Block/Actions/DownloadAction.swift
Sources/ZcashLightClientKit/Block/Actions/FetchUTXOsAction.swift
Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Block/Actions/ValidateAction.swift

Closes #1047 
- scan action with the proper ranges computed

[#1047] Implement ScanAction

---

Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift

[#1044] Implement EnhanceAction

---

Sources/ZcashLightClientKit/Block/Actions/ClearCacheAction.swift

[#1041] Implement ClearCacheAction

---

Sources/ZcashLightClientKit/Block/Actions/ClearAlreadyScannedBlocksAction.swift

[#1040] Implement ClearAlreadyScannedBlocksAction

---

Sources/ZcashLightClientKit/Block/Actions/ChecksBeforeSyncAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessorNG.swift

[#1039] Implement ChecksBeforeSyncAction

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Tests/NetworkTests/BlockScanTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift

Some tests are disabled for now (list is in #1115). And `NetworkTests` can be compiled and all the enabled tests work.

[#700] Make NetworkTests compilable

---

Sources/ZcashLightClientKit/Block/Actions/MigrateLegacyCacheDBAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Synchronizer/Dependencies.swift
Sources/ZcashLightClientKit/Utils/ZcashFileManager.swift
Tests/OfflineTests/CompactBlockProcessorActions/ChecksBeforeSyncActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ComputeSyncRangesActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/DownloadActionTests.swift
Tests/TestUtils/Sourcery/AutoMockable.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift

Closes #1122 
- ZcashFileManager implemented
- MigrateLegacyCacheDBAction refactored to be dependent on ZcashFileManager
- ZcashFileManager mock added

[#1122] Implement FileManager protocol and dependency

---

Tests/OfflineTests/CompactBlockProcessorActions/ClearAlreadyScannedBlocksActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ClearCacheActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/MigrateLegacyCacheDBActionTests.swift

Closes #1121 
- MigrateLegacyCacheDBAction tests
- tests naming cleanup

[#1121] Implement MigrateLegacyCacheDBAction

---

Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/SynchronizerDarksideTests.swift

[#1128] Fix switch to error state after Synchronizer.prepare() call

---

Tests/OfflineTests/CompactBlockProcessorActions/ClearAlreadyScannedBlocksActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ClearCacheActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/DownloadActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/MigrateLegacyCacheDBActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ScanActionTests.swift

 [#1129] Final check of all State Machine Action tests

---

Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/SynchronizerDarksideTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/EnhanceActionTests.swift

Some actions in the sync process may not run. For example there are no transactions to enhance and therefore there is no enhance progress. And in cases like this computation of final progress won't work properly. So let's fake 100% progress at the end of the sync process.

[#700] Fix progress reporting

---

Sources/ZcashLightClientKit/Synchronizer.swift

Fix inverted sync status flags

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Tests/TestUtils/Resources/sandblasted_mainnet_block.json

The previous FFI repo revision no longer exists; commits between 87faf91096b7abc9d1eacb5eaf3e6d7fc2ddb9ef and here will not build.

Update Rust dependencies with bugfixes

---

Sources/ZcashLightClientKit/Block/Actions/ComputeSyncControlDataAction.swift
Sources/ZcashLightClientKit/Providers/LatestBlocksDataProvider.swift
Tests/OfflineTests/CompactBlockProcessorActions/ComputeSyncControlDataActionTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Stubs.swift

Closes #1184 
- firstUnenhancedHeight is now properly used
- fixed tests

[#1184] FirstUnenhancedHeight not called

---

CHANGELOG.md
Sources/ZcashLightClientKit/Utils/OSLogger.swift

Closes #1196 
- the priorities for log levels have been updated

[#1196] Check logging level priorities

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

The previous FFI repo revisions no longer exist; commits between 87faf91096b7abc9d1eacb5eaf3e6d7fc2ddb9ef and here will not build.

Update Rust dependencies with scanning and spending bugfixes

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift

Closes #1208 
- hotfix for explicit use of self in a Task, CI fails to build it without it

[#1208] Bitrise fails to build

---

Sources/ZcashLightClientKit/Block/Actions/Action.swift
Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift
Sources/ZcashLightClientKit/Block/Actions/ProcessSuggestedScanRangesAction.swift
Sources/ZcashLightClientKit/Block/Actions/UpdateChainTipAction.swift
Tests/OfflineTests/CompactBlockProcessorActions/EnhanceActionTests.swift

Closes #1206 
- The State Machine has been slightly updated so it measures time when it lastly updated chain tip. If it happened more than 10mins ago, it calls the .updateChainTip action once again before the download-scan-enhance loop continues
- updated unit test

[#1206] Frequent call of update chain tip

---

Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift

Closes #1213 
- endpoint updated to the latest and workable server

[#1213] Server update

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

Update the `zcash-light-client-ffi` dependency version.

---

Sources/ZcashLightClientKit/Block/Actions/UpdateChainTipAction.swift
Tests/OfflineTests/CompactBlockProcessorActions/UpdateChainTipActionTests.swift

Closes #1227 
- My assumption was right, the way State Machine is done requires .celarCache to be called with every "restart"
- I was able to reproduce errors when clearCache wasn't called so the updateChainTipAction needed to be updated to prepare clean conditions for the scan suggest ranges
- tests updated

[#1227] Check continuation of UpdateChainTip repeated call

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

The previous `zcash-light-client-ffi` revisions should be treated as ephemeral; they will be removed upon creation of the SDK 2.0.0 release candidate.

Update Rust dependencies with bugfixes.

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksListViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Sources/ZcashLightClientKit/ClosureSynchronizer.swift
Sources/ZcashLightClientKit/CombineSynchronizer.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/ClosureSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/CombineSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
Tests/OfflineTests/SynchronizerOfflineTests.swift
Tests/OfflineTests/WalletTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/TestCoordinator.swift

Closes #1236 
- SDKSynchronizer's public API prepareWith() now requires a parameter WalletInitMode
- tests fixed

[#1236] Use of recoverUntil

---

Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockReorgTests.swift

Closes #1252 
- NetworkTests are buildable and can run not crashing due to lack of mocked properties
- most tests have been fixed and pass again

[#1252] NetworkTests fails to run

---

CHANGELOG.md

Closes #1255 
- cleanup and fixes

[#1255] Changelog tweak

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

* Updates to `zcash-light-client-ffi 0.4.0-rc.1`
* Updates to `zcash-light-client-ffi 637d411b708cda64cf4b601548d2f70d2d2c324d` to fix a bug discovered after 0.4.0-rc1
* Makes some cleanup updates to the CHANGELOG; a complete changelog will be prepared for the 2.0.0 final release.

Update zcash-light-client-ffi dependency for release candidate prep.

---

Sources/ZcashLightClientKit/Model/ScanProgress.swift
Tests/OfflineTests/ZcashRustBackendTests.swift

Although is not the best way to solve it this addresses the issue in a single statement and following existing pattern in the code.
The error should be thrown earlier in RustBackend itself if so, or fallback to some specific value that makes sense to the domain
Closes #1267

[#1267] Avoid Division By Zero in ScanProgress type

---

Sources/ZcashLightClientKit/Block/Scan/BlockScanner.swift

The improved performance provided by `shardtree` is sufficient to allow 100-block scan ranges throughout the sandblasted range, and limiting to 10 blocks results in significant overhead.
A future release will switch to an adaptive strategy which can dynamically adjust download and scan range sizes based upon observed output counts and scanning times to provide consistent throughput.

Remove the 10-block range limit for during sandblasting.

---

Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift

Closes #1262 
- rootsPtr deallocated

[#1262] Check pairing of deallocations vs allocations in rustBackend

---

Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Block/Actions/UpdateChainTipAction.swift
Sources/ZcashLightClientKit/Providers/LatestBlocksDataProvider.swift
Tests/OfflineTests/CompactBlockProcessorActions/ScanActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/UpdateChainTipActionTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift

Closes #1273 
- latestBlockHeight (chain tip) reported in the SynchronizerState to the clients is now updated every 10mins at most, typically with every sync run (10-30s)
- fully and max scanned heights update fixed
- new mocks provided and tests fixed

[#1273] SynchronizerState not always up to date

---

Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/DAO/UnspentTransactionOutputDao.swift
Sources/ZcashLightClientKit/Entity/AccountEntity.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift

Closes #1281 
- Execution of any query in TransactionSQLDAO was not thread safe. Since all queries goes through execute() method, this is now using a lock

[#1281] Database is locked

---

Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksListViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Sources/ZcashLightClientKit/Synchronizer.swift

Closes #1288 
- InternalSyncStatus as well as SyncStatus were extended with stopped state, this is needed to distinguish between upToDate and stopped via stop() method states as previously stopped state of block processor was mapped to upToDate

[#1288] Extend SyncStatus with stopped state

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

Update `zcash-light-client-ffi` and other dependencies for 2.0.0 final release.

---

CHANGELOG.md
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/ShieldFundsTests.swift
Tests/DarksideTests/SynchronizerTests.swift
Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/TestsData.swift

Closes #1294 
- Removed deprecated zip-313 fee of 1000 Zatoshi
- default is now 10k zatoshi, the minimum defined by zip-317

[#1294] Remove all uses of the incorrect 1000-ZAT fee

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Tests/OfflineTests/CompactBlockProcessorActions/ActionContextStateTests.swift

Closes #1301 
- There was a reset missing in the rewind() call. This method is a direct call affecting the state of the compact block processor but the ActionContext has been handled only in the synchronization pipeline. Manual reset was needed to reset the last enhanced height.
- tests added

[#1301] foundTransactions don't emit after rewind

---

CHANGELOG.md
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift

Closes #1303 
- the most simple fix for this issue is to set the number of attempts to the "infinity"
- smarter solution will require a better retry logic in general, covered in #1304

[#1303] Don't invalidate the timer with the error

---

.github/workflows/swift.yml

[#1318] Fix build github action failing

---

CHANGELOG.md

Closes #1328 
- Changelog updated with the date

[#1328] Release 2.0.4

---

CHANGELOG.md
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift

Closes #1346 
- changelog update
- the sync time has been reduced by ~33%. The progress reporting frequency has been lowered down 5-times
- this is just first step and a quick improvement before we introduce advanced solution, covered in #1353

[#1346] Troubleshooting synchronization

---

CHANGELOG.md
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift

Closes #1351 
- block stream errors are now handled as a special case of error, retry logic is triggered but at most 3-times in case of service being truly down
- the failure is not passed to the clients so ideally the false positive errors are reduced as well as the delay in the sync time

[#1351] Recover from block stream issues

---

CHANGELOG.md

[#1359] Release 2.0.6

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

Release version 2.0.8

---

CHANGELOG.md
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Model/WalletSummary.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/SynchronizerDarksideTests.swift
Tests/OfflineTests/SynchronizerOfflineTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Sourcery/generateMocks.sh
Tests/TestUtils/Stubs.swift

Closes #1363 
- changelog update
- scanAction reports the initial after-scan value immediately instead of after X scans
- SynchronizerState has been refactored, we no longer call 2 rust methods to get shielded verified + total balances
- tests refactored to reflect this change
- mocks regenerated
- Sourcery version bumped

[#1363] Account balances in the SynchronizerState

---

Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift

Closes #1368 
- The retry logic was implemented for blockStream errors only but this PR generalize it for any lightwalletd error

[#1368] Handle any lightwalletd error with retry logic

---

CHANGELOG.md
Sources/ZcashLightClientKit/Model/Proposal.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift

Closes #1186 
- Proposal conforms to the Equatable
- `.testOnlyFakeProposal` Proposal added
- `useZIP317Fees` has been enabled

TCA-conformations

---

Sources/ZcashLightClientKit/Synchronizer.swift

- TransactionSubmitResult now conforms to Equatable protocol

Equatable TransactionSubmitResult

---

Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/PaymentURIFulfillmentTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift

- New public API `isSeedRelevantToWallet` has been implemented
- 2 swiftlint error have been resolved
- Mocks generated

Public API isSeedRelevantToWallet

---

Sources/ZcashLightClientKit/Entity/TransactionEntity.swift

Orchard implementation fixes

---

CHANGELOG.md

- changelog updated for the release

[#1398] Release 2.1.0

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift

[#1402] Release 2.1.1

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift

Closes #1404 
- fix for a bug in note selection when sending to a transparent recipient

[#1404] Release 2.1.2

---

CHANGELOG.md

[#1406] Release 2.1.3

---

Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
Sources/ZcashLightClientKit/Utils/DBActor.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ProcessSuggestedScanRangesActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/RewindActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ScanActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/UpdateChainTipActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/UpdateSubtreeRootsActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ValidateServerActionTests.swift
Tests/OfflineTests/FsBlockStorageTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Stubs.swift
Tests/TestUtils/TestDbBuilder.swift

Closes #1177 
- globalDBLock has been removed and replaced with global DBActor

[#1177] Remove globalDBLock

---

CHANGELOG.md
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Providers/LatestBlocksDataProvider.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift

Closes #1412 
- The wipe() is now resetting local in memory values of latestBlocksDataProvider. In some case this could cause a reset of CBP's state machine context sooner than it was supposed to, resulting in corrupted sync.

[#1412] Review wipe function and in memory values

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Sourcery/generateMocks.sh
Tests/TestUtils/Stubs.swift

Update to zcash-light-client-ffi version 0.8.0.

---

CHANGELOG.md

[#1418] Release 2.1.5

---

CHANGELOG.md

[#1425] Release 2.1.6

---

Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift

Allow shielding with one confirmation for incoming transparent funds.

---

CHANGELOG.md

[#1427] Release 2.1.7

---

CHANGELOG.md
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Repository/TransactionRepository.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/TestUtils/MockTransactionRepository.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Sourcery/generateMocks.sh

Closes #1429 
- New API for getting the memos by transaction's rawID

[#1429] Get memos for rawID

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
Example/ZcashLightClientSample/ZcashLightClientSample/List Transactions/TransactionsDataSource.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Transaction Detail/TransactionDetailViewController.swift
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Block/Enhance/BlockEnhancer.swift
Sources/ZcashLightClientKit/Checkpoint/BundleCheckpointSource.swift
Sources/ZcashLightClientKit/Checkpoint/CheckpointSourceFactory.swift
Sources/ZcashLightClientKit/CombineSynchronizer.swift
Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Synchronizer/CombineSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/PaymentURIFulfillmentTests.swift
Tests/OfflineTests/CheckpointSourceTests.swift
Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ActionContextStateTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ProcessSuggestedScanRangesActionTests.swift

Closes #1431 
- all reported swiftlint issues have been addressed

[#1431] Fix swiftlint reported issues

---

CHANGELOG.md

[#1435] Release 2.1.8

---

CHANGELOG.md
Sources/ZcashLightClientKit/Initializer.swift

Closes #1440 
- Prepare of the synchronizer should be possible even if the server is down, fetching chain tip was forced and newly is optional

[#1440] Optional chainTip for account creation

---

CHANGELOG.md

[#1444] Release 2.1.9

---

CHANGELOG.md

[#1448] Release 2.1.10

---

Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/FakeChainBuilder.swift

this adds the addTreeState() function to the DarksideWalletService class and corresponding calls in FakeChainBuilder
Closes #1455

[#1455] Darkside Tests: Test fail with "call AddTreeState() first"

---

CHANGELOG.md
Sources/ZcashLightClientKit/Block/Actions/UpdateChainTipAction.swift
Tests/DarksideTests/DarksideSanityCheckTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/UpdateChainTipActionTests.swift
Tests/TestUtils/FakeChainBuilder.swift

Closes #1462 
- The CompactBlockProcessor's state machine got stuck in some cases at the updateChainTip action.

[#1462] Syncing is broken

---

CHANGELOG.md

Closes #1464 
- Version set to 2.1.12

[#1464] Release 2.1.12

---

Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
Sources/ZcashLightClientKit/Tool/DerivationTool.swift
Tests/OfflineTests/DerivationToolTests/DerivationToolTestnetTests.swift
Tests/OfflineTests/ZcashRustBackendTests.swift

This enables us to simplify the FFI backend.

Use `DerivationTool.getAddressMetadata` inside `DerivationTool.isValid*`

---

Sources/ZcashLightClientKit/Model/FiatCurrencyResult.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Tor/TorClient.swift

- The API has been refactored to carry state and always broadcast a value, even in case of failed request
- ignore refresh request when one is already in flight

always-return-value

---

Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Tor/TorClient.swift

comments-fixed

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

This release fixes an error in database migrations that could cause problems when upgrading from version in the 2.1.x range.

release zcash-swift-wallet-sdk version 2.2.1

---

Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift

Closes #1483 
- endTime update removed

[#1483] Fix evaluateOf endTime

---

Package.swift
Sources/ZcashLightClientKit/DAO/TransactionDao.swift
Sources/ZcashLightClientKit/Entity/TransactionEntity.swift

Closes #1488 
- SQLight's Expression conflicted with the swift's expressions, solved by adding a namespace so it's clear which one is which

[#1488] Resolve build issues with SQLight

---

CHANGELOG.md

[#1496] Release 2.2.4

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/RewindActionTests.swift
Tests/TestUtils/DarkSideWalletService.swift
Tests/TestUtils/FakeService.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Stubs.swift

Release zcash-swift-wallet-sdk version 2.2.5

---

Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift

Ensure that scan progress can't exceed 100%

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

zcash-swift-wallet-sdk release version 2.2.6

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample/Get Balance/GetBalanceViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift
Sources/ZcashLightClientKit/Block/SaplingParameters/SaplingParametersHandler.swift
Sources/ZcashLightClientKit/ClosureSynchronizer.swift
Sources/ZcashLightClientKit/Metrics/SDKMetrics.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/ClosureSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/CombineSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/AdvancedReOrgTests.swift
Tests/DarksideTests/BalanceTests.swift
Tests/DarksideTests/RewindRescanTests.swift
Tests/DarksideTests/ShieldFundsTests.swift
Tests/DarksideTests/SynchronizerTests.swift
Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift

Closes #1512 
- The SDK no longer assumes a default account. All business logic with instances of Zip32AccountIndex(x) has been refactored.

[#1512] Ensure that the SDK does not assume a default account anywhere

---

CHANGELOG.md

[#1531] Release 2.2.9

---

CHANGELOG.md

[#1535] Release 2.2.10

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksListViewController.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksViewController.swift
Package.swift
Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Block/Utils/CompactBlockProgress.swift
Sources/ZcashLightClientKit/Checkpoint/BundleCheckpointSource.swift
Sources/ZcashLightClientKit/Checkpoint/CheckpointSource.swift
Sources/ZcashLightClientKit/ClosureSynchronizer.swift
Sources/ZcashLightClientKit/CombineSynchronizer.swift
Sources/ZcashLightClientKit/Model/WalletSummary.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/ClosureSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/CombineSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Tests/DarksideTests/SynchronizerDarksideTests.swift
Tests/OfflineTests/SynchronizerOfflineTests.swift
Tests/OfflineTests/ZcashRustBackendTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Stubs.swift

[#1537] birthday estimate based on a date, scan & recovery progresses

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift

Closes #1544 
- FFI version bumped to 0.15.0
- Param files directed to the CDN

[#1544] Release 2.2.13

---

CHANGELOG.md

[#1547] Release 2.2.14

---

CHANGELOG.md
Sources/ZcashLightClientKit/Block/Enhance/BlockEnhancer.swift

[#1556] Release 2.2.16

---

Sources/ZcashLightClientKit/Block/Actions/ScanAction.swift
Sources/ZcashLightClientKit/Model/WalletSummary.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift

Closes #1566 
This check was done as a float comparison with unreliable results. Changed to address that with nominator & denominator integers.

[#1566] 100 percent scan progress check

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample/AppDelegate.swift
Example/ZcashLightClientSample/ZcashLightClientSample/Sync Blocks/SyncBlocksListViewController.swift
Sources/ZcashLightClientKit/Block/CompactBlockProcessor.swift
Sources/ZcashLightClientKit/Constants/ZcashSDK.swift
Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
Sources/ZcashLightClientKit/Initializer.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/Dependencies.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Tor/TorClient.swift
Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
Sources/ZcashLightClientKit/Utils/SDKFlags.swift
Tests/DarksideTests/TransactionEnhancementTests.swift
Tests/NetworkTests/BlockStreamingTest.swift
Tests/NetworkTests/CompactBlockProcessorTests.swift
Tests/NetworkTests/CompactBlockReorgTests.swift
Tests/NetworkTests/DownloadTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/UpdateChainTipActionTests.swift
Tests/OfflineTests/CompactBlockProcessorActions/ValidateServerActionTests.swift
Tests/OfflineTests/InitializerOfflineTests.swift
Tests/OfflineTests/SynchronizerOfflineTests.swift
Tests/OfflineTests/WalletTests.swift
Tests/PerformanceTests/SynchronizerTests.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/TestCoordinator.swift
Tests/TestUtils/TestsData.swift

Closes #1582 
- download batch has been increased to 100 instead of 10 blocks
- raw transactions have been enxtended to hold a state (expired, confirmed or pending)
- Tor setup has been refactored to be independent between exchange rate and lwd/http calls

[#1582] Tor and sync optimizations and changes

---

CHANGELOG.md
Sources/ZcashLightClientKit/ClosureSynchronizer.swift
Sources/ZcashLightClientKit/CombineSynchronizer.swift
Sources/ZcashLightClientKit/Error/ZcashError.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCode.swift
Sources/ZcashLightClientKit/Error/ZcashErrorCodeDefinition.swift
Sources/ZcashLightClientKit/Synchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/ClosureSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/CombineSDKSynchronizer.swift
Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Sources/ZcashLightClientKit/Tor/TorClient.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift

Closes #1575 
- Public APIs for the httpRequest via TorClient

[#1575] GET and POST requests over Tor API

---

Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
Tests/TestUtils/Sourcery/generateMocks.sh

Expose txid from decryptAndStore across the FFI

---

CHANGELOG.md
Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift

[#1600] Release 2.3.4
